DNA Origami
---
Written by Sarah Hong, adapted from Jason Kahn

In [2]:
# For reading/writing lattice from file
import os
import sys
import numpy as np # The backbone of this program

# vispy imports
from vispy import app, scene
from vispy.color import Color

# My imports
from visualizations.LatticeCreator import LatticeCreatorGUI
from visualizations.LatticeVisualizer import LatticeVisualizer
from algorithm.Voxel import Voxel
from algorithm.Lattice import Lattice
from algorithm.Surroundings import SurroundingsManager
from algorithm.Symmetry import SymmetryManager

In [3]:
%gui tk

lc_gui = LatticeCreatorGUI()
input_lattice, isUnitCell = lc_gui.run()

print("The final lattice is:")
print(input_lattice)
print("Is it a unit cell? ", isUnitCell)

if input_lattice is not None:
    np.save("lattice.npy", input_lattice)

The final lattice is:
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[0. 1. 0.]
  [0. 1. 0.]]

 [[0. 1. 0.]
  [0. 1. 0.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
Is it a unit cell?  1


invalid command name "4434062336update"
    while executing
"4434062336update"
    ("after" script)
invalid command name "4798773568check_dpi_scaling"
    while executing
"4798773568check_dpi_scaling"
    ("after" script)
invalid command name "6084220928_click_animation"
    while executing
"6084220928_click_animation"
    ("after" script)


In [5]:
%gui qt

with open('lattice.npy', 'rb') as f:
    input_lattice = np.load(f)

print(input_lattice)

vis = LatticeVisualizer(input_lattice)
vis.run()

ERROR:root:Cannot activate multiple GUI eventloops


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[0. 1. 0.]
  [0. 1. 0.]]

 [[0. 1. 0.]
  [0. 1. 0.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [6]:
input_lattice = np.load('lattice.npy')
lattice = Lattice(input_lattice)
sm = SurroundingsManager(lattice)

In [16]:
# %gui qt

# Visualize the UnitCell
# UC_vis = LatticeVisualizer(lattice.UnitCell)
# UC_vis.run()

# Visualize the MinDesign
# MD_vis = LatticeVisualizer(lattice.MinDesign)
# MD_vis.run()

In [7]:
# %gui qt

# Visualize the FullSurroundings 
# (Not recommended for large designs, it's extremely slow even for simple ones)

# FS_vis = LatticeVisualizer(sm.FullSurroundings)
# FS_vis.run()

print(f'FullSurroundings:\n{sm.FullSurroundings}')
print(f'Shape: {sm.FullSurroundings.shape}')

FullSurroundings:
[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
  [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
  [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
  [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
  [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
  [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
  [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
  [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
  [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]]

 [[0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
  [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
  [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
  [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
  [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
  [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
  [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
  [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
  [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 

In [8]:
%gui qt
# Get VoxelSurroundings for voxel at (0, 0, 0)

print(f'Original lattice: \n{lattice.MinDesign}\n')
voxel = lattice.voxels[0]
print(f'Voxel {voxel.index} has coordinates: {voxel.coordinates} in original lattice')

vox_surround = sm.getVoxelSurroundings(voxel)
VS_vis = LatticeVisualizer(vox_surround)
VS_vis.run()

print(f'Surrounding matrix for Voxel {voxel.index}:\n{vox_surround}')

ERROR:root:Cannot activate multiple GUI eventloops


Original lattice: 
[[[1. 1.]]

 [[0. 1.]]

 [[0. 1.]]]

Voxel 0 has coordinates: (0, 0, 0) in original lattice
Surrounding matrix for Voxel 0:
[[[1. 0. 1.]
  [1. 0. 1.]
  [1. 0. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 0. 1.]
  [1. 0. 1.]
  [1. 0. 1.]]]


## Test: SymmetryManager
Demonstrates example workflow, loading in an existing lattice from `lattice.npy`

In [9]:
from algorithm.Voxel import Voxel
from algorithm.Lattice import Lattice
from algorithm.Surroundings import SurroundingsManager
from algorithm.Symmetry import SymmetryManager

import numpy as np

print("SymmetryManager tests\n---\n")

input_lattice = np.load('lattice.npy')
print(f'Input lattice:\n{input_lattice}\n')

lattice = Lattice(input_lattice)
print(f'Min design:\n{lattice.MinDesign}\n')
print(f'Voxels:\n{lattice.voxels}\n')
print(f'Voxel indices:\n{[voxel.index for voxel in lattice.voxels]}\n')

surr_manager = SurroundingsManager(lattice)
print(f'Full surroundings:\n{surr_manager.FullSurroundings}\n')
print(f'VoxelSurroundings for voxel 0:\n{surr_manager.getVoxelSurroundings(lattice.voxels[0])}\n')
print(f'VoxelSurroundings for voxel 1:\n{surr_manager.getVoxelSurroundings(lattice.voxels[1])}\n')

sym_manager = SymmetryManager(lattice, surr_manager)
sym_manager.checkAllSymmetries()
df = sym_manager.getSymmetryDataframe()

SymmetryManager tests
---

Input lattice:
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[0. 1. 0.]
  [0. 1. 0.]]

 [[0. 1. 0.]
  [0. 1. 0.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]

Min design:
[[[1. 1.]]

 [[0. 1.]]

 [[0. 1.]]]

Voxels:
[<algorithm.Voxel.Voxel object at 0x2981ac440>, <algorithm.Voxel.Voxel object at 0x2981acb90>, <algorithm.Voxel.Voxel object at 0x175bf5c10>, <algorithm.Voxel.Voxel object at 0x175d27380>, <algorithm.Voxel.Voxel object at 0x175e29490>, <algorithm.Voxel.Voxel object at 0x298034320>]

Voxel indices:
[0, 1, 2, 3, 4, 5]

Full surroundings:
[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
  [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
  [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
  [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
  [0. 

AttributeError: 'SymmetryManager' object has no attribute 'printSymmetryDict'

In [1]:
# Tests 2
from algorithm.Voxel import Voxel
from algorithm.Lattice import Lattice
from algorithm.Surroundings import SurroundingsManager
from algorithm.Symmetry import SymmetryManager

import numpy as np
import pandas as pd

print("SymmetryManager tests\n---\n")

input_lattice = np.load('lattice.npy')
print(f'Input lattice:\n{input_lattice}\n')

lattice = Lattice(input_lattice)
print(f'Min design:\n{lattice.MinDesign}\n')
print(f'Voxels:\n{lattice.voxels}\n')
print(f'Voxel indices:\n{[voxel.index for voxel in lattice.voxels]}\n')

surr_manager = SurroundingsManager(lattice)
print(f'Full surroundings:\n{surr_manager.FullSurroundings}\n')
print(f'VoxelSurroundings for voxel 0:\n{surr_manager.getVoxelSurroundings(lattice.voxels[0])}\n')
print(f'VoxelSurroundings for voxel 1:\n{surr_manager.getVoxelSurroundings(lattice.voxels[1])}\n')

sym_manager = SymmetryManager(lattice, surr_manager)
sym_manager.checkAllSymmetries()
df = sym_manager.getSymmetryDict_df()

df

SymmetryManager tests
---

Input lattice:
[[[1. 1.]
  [1. 1.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]

Min design:
[[[1. 1.]
  [1. 1.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]

Voxels:
[<algorithm.Voxel.Voxel object at 0x118b81370>, <algorithm.Voxel.Voxel object at 0x118af36b0>, <algorithm.Voxel.Voxel object at 0x118a1d280>, <algorithm.Voxel.Voxel object at 0x118a1d610>, <algorithm.Voxel.Voxel object at 0x11d95fe90>, <algorithm.Voxel.Voxel object at 0x11d3c4290>, <algorithm.Voxel.Voxel object at 0x10e5d2f30>, <algorithm.Voxel.Voxel object at 0x11dba1a30>, <algorithm.Voxel.Voxel object at 0x11da53d10>, <algorithm.Voxel.Voxel object at 0x1189f5490>, <algorithm.Voxel.Voxel object at 0x1189f59a0>, <algorithm.Voxel.Voxel object at 0x1189f5640>]

Voxel indices:
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

Full surroundings:
[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1

Voxel Pair  90° Rotation in x axis  180° Rotation in x axis  \
0        (0,)                    True                     True   
1      (1, 0)                    True                     True   
2      (2, 0)                    True                     True   
3      (3, 0)                    True                     True   
4      (4, 0)                   False                    False   
..        ...                     ...                      ...   
73    (9, 10)                    True                     True   
74    (9, 11)                    True                     True   
75      (10,)                    True                     True   
76   (10, 11)                    True                     True   
77      (11,)                    True                     True   

    270° Rotation in x axis  90° Rotation in y axis  180° Rotation in y axis  \
0                      True                   False                     True   
1                      True                   False                     True   
2                      True                   False                     True   
3                      True                   False                     True   
4                     False                   False                    False   
..                      ...                     ...                      ...   
73                     True                   False                    False   
74                     True                   False                    False   
75                     True                   False                    False   
76                     True                   False                    False   
77                     True                   False                    False   

    270° Rotation in y axis  90° Rotation in z axis  180° Rotation in z axis  \
0                     False                   False                     True   
1                     False                   False                     True   
2                     False                   False                     True   
3                     False                   False                     True   
4                     False                   False                    False   
..                      ...                     ...                      ...   
73                    False                   False                    False   
74                    False                   False                    False   
75                    False                   False                    False   
76                    False                   False                    False   
77                    False                   False                    False   

    270° Rotation in z axis  
0                     False  
1                     False  
2                     False  
3                     False  
4                     False  
..                      ...  
73                    False  
74                    False  
75                    False  
76                    False  
77                    False  

[78 rows x 10 columns]

In [10]:
df

Voxel Pair  90° Rotation in x axis  180° Rotation in x axis  \
0        (0,)                    True                     True   
1      (1, 0)                    True                     True   
2      (2, 0)                    True                     True   
3      (3, 0)                    True                     True   
4      (4, 0)                   False                    False   
..        ...                     ...                      ...   
73    (9, 10)                    True                     True   
74    (9, 11)                    True                     True   
75      (10,)                    True                     True   
76   (10, 11)                    True                     True   
77      (11,)                    True                     True   

    270° Rotation in x axis  90° Rotation in y axis  180° Rotation in y axis  \
0                      True                   False                     True   
1                      True                   False                     True   
2                      True                   False                     True   
3                      True                   False                     True   
4                     False                   False                    False   
..                      ...                     ...                      ...   
73                     True                   False                    False   
74                     True                   False                    False   
75                     True                   False                    False   
76                     True                   False                    False   
77                     True                   False                    False   

    270° Rotation in y axis  90° Rotation in z axis  180° Rotation in z axis  \
0                     False                   False                     True   
1                     False                   False                     True   
2                     False                   False                     True   
3                     False                   False                     True   
4                     False                   False                    False   
..                      ...                     ...                      ...   
73                    False                   False                    False   
74                    False                   False                    False   
75                    False                   False                    False   
76                    False                   False                    False   
77                    False                   False                    False   

    270° Rotation in z axis  
0                     False  
1                     False  
2                     False  
3                     False  
4                     False  
..                      ...  
73                    False  
74                    False  
75                    False  
76                    False  
77                    False  

[78 rows x 10 columns]