DNA Origami
---
Written by Sarah Hong, adapted from Jason Kahn

In [6]:
# For reading/writing lattice from file
import os
import sys
import numpy as np # The backbone of this program

# vispy imports
from vispy import app, scene
from vispy.color import Color

# My imports
from visualizations.LatticeCreator import LatticeCreatorGUI
from visualizations.LatticeVisualizer import LatticeVisualizer
from algorithm.Voxel import Voxel
from algorithm.Lattice import Lattice
from algorithm.Surroundings import SurroundingsManager
from algorithm.Symmetry import SymmetryManager

In [8]:
%gui tk

lc_gui = LatticeCreatorGUI()
input_lattice, isUnitCell = lc_gui.run()

print("The final lattice is:")
print(input_lattice)
print("Is it a unit cell? ", isUnitCell)

if input_lattice is not None:
    np.save("lattice.npy", input_lattice)

The final lattice is:
[[[1. 1.]
  [1. 1.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
Is it a unit cell?  1


invalid command name "4830563904update"
    while executing
"4830563904update"
    ("after" script)
invalid command name "4829141440check_dpi_scaling"
    while executing
"4829141440check_dpi_scaling"
    ("after" script)
invalid command name "4829144704_click_animation"
    while executing
"4829144704_click_animation"
    ("after" script)


In [9]:
%gui qt

with open('lattice.npy', 'rb') as f:
    lattice = np.load(f)

print(lattice)

vis = LatticeVisualizer(lattice)
vis.run()

ERROR:root:Cannot activate multiple GUI eventloops


[[[1. 1.]
  [1. 1.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [15]:
input_lattice = np.load('lattice.npy')
lattice = Lattice(input_lattice)
sm = SurroundingsManager(lattice)

In [16]:
# %gui qt

# Visualize the UnitCell
# UC_vis = LatticeVisualizer(lattice.UnitCell)
# UC_vis.run()

# Visualize the MinDesign
# MD_vis = LatticeVisualizer(lattice.MinDesign)
# MD_vis.run()

In [17]:
# %gui qt

# Visualize the FullSurroundings 
# (Not recommended for large designs, it's extremely slow even for simple ones)

# FS_vis = LatticeVisualizer(sm.FullSurroundings)
# FS_vis.run()

print(f'FullSurroundings:\n{sm.FullSurroundings}')
print(f'Shape: {sm.FullSurroundings.shape}')

FullSurroundings:
[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.

In [20]:
%gui qt
# Get VoxelSurroundings for voxel at (0, 0, 0)

print(f'Original lattice: \n{lattice.MinDesign}\n')
voxel = lattice.voxels[0]
print(f'Voxel {voxel.index} has coordinates: {voxel.coordinates} in original lattice')

vox_surround = sm.getVoxelSurroundings(voxel)
VS_vis = LatticeVisualizer(vox_surround)
VS_vis.run()

print(f'Surrounding matrix for Voxel {voxel.index}:\n{vox_surround}')

ERROR:root:Cannot activate multiple GUI eventloops


Original lattice: 
[[[1. 1.]
  [1. 1.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]

Voxel 0 has coordinates: (0, 0, 0) in original lattice
Surrounding matrix for Voxel 0:
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [21]:
SymManager = SymmetryManager(lattice, sm)

voxel1 = lattice.voxels[0]
voxel2 = lattice.voxels[1]

has_sym = SymManager.hasSymmetry(voxel1, voxel2, '90° Rotation in x axis')

print(f'Does Voxel {voxel1.index} have 90° rotational symmetry in x-axis with Voxel {voxel2.index}?:')
print(has_sym)

Does Voxel 0 have 90° rotational symmetry in x-axis with Voxel 1?:
True
