DNA Origami
---
Written by Sarah Hong, adapted from Jason Kahn

In [2]:
# For reading/writing lattice from file
import os
import sys
import numpy as np # The backbone of this program

# vispy imports
from vispy import app, scene
from vispy.color import Color

# My imports
from visualizations.LatticeCreator import LatticeCreatorGUI
from visualizations.LatticeVisualizer import LatticeVisualizer
from algorithm.Voxel import Voxel
from algorithm.Lattice import Lattice
from algorithm.Surroundings import SurroundingsManager
from algorithm.Symmetry import SymmetryManager

In [3]:
%gui tk

lc_gui = LatticeCreatorGUI()
input_lattice, isUnitCell = lc_gui.run()

print("The final lattice is:")
print(input_lattice)
print("Is it a unit cell? ", isUnitCell)

if input_lattice is not None:
    np.save("lattice.npy", input_lattice)

The final lattice is:
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[0. 1. 0.]
  [0. 1. 0.]]

 [[0. 1. 0.]
  [0. 1. 0.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
Is it a unit cell?  1


invalid command name "4434062336update"
    while executing
"4434062336update"
    ("after" script)
invalid command name "4798773568check_dpi_scaling"
    while executing
"4798773568check_dpi_scaling"
    ("after" script)
invalid command name "6084220928_click_animation"
    while executing
"6084220928_click_animation"
    ("after" script)


In [5]:
%gui qt

with open('lattice.npy', 'rb') as f:
    input_lattice = np.load(f)

print(input_lattice)

vis = LatticeVisualizer(input_lattice)
vis.run()

ERROR:root:Cannot activate multiple GUI eventloops


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[0. 1. 0.]
  [0. 1. 0.]]

 [[0. 1. 0.]
  [0. 1. 0.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [6]:
input_lattice = np.load('lattice.npy')
lattice = Lattice(input_lattice)
sm = SurroundingsManager(lattice)

In [16]:
# %gui qt

# Visualize the UnitCell
# UC_vis = LatticeVisualizer(lattice.UnitCell)
# UC_vis.run()

# Visualize the MinDesign
# MD_vis = LatticeVisualizer(lattice.MinDesign)
# MD_vis.run()

In [7]:
# %gui qt

# Visualize the FullSurroundings 
# (Not recommended for large designs, it's extremely slow even for simple ones)

# FS_vis = LatticeVisualizer(sm.FullSurroundings)
# FS_vis.run()

print(f'FullSurroundings:\n{sm.FullSurroundings}')
print(f'Shape: {sm.FullSurroundings.shape}')

FullSurroundings:
[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
  [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
  [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
  [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
  [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
  [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
  [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
  [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
  [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]]

 [[0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
  [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
  [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
  [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
  [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
  [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
  [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
  [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
  [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 

In [8]:
%gui qt
# Get VoxelSurroundings for voxel at (0, 0, 0)

print(f'Original lattice: \n{lattice.MinDesign}\n')
voxel = lattice.voxels[0]
print(f'Voxel {voxel.index} has coordinates: {voxel.coordinates} in original lattice')

vox_surround = sm.getVoxelSurroundings(voxel)
VS_vis = LatticeVisualizer(vox_surround)
VS_vis.run()

print(f'Surrounding matrix for Voxel {voxel.index}:\n{vox_surround}')

ERROR:root:Cannot activate multiple GUI eventloops


Original lattice: 
[[[1. 1.]]

 [[0. 1.]]

 [[0. 1.]]]

Voxel 0 has coordinates: (0, 0, 0) in original lattice
Surrounding matrix for Voxel 0:
[[[1. 0. 1.]
  [1. 0. 1.]
  [1. 0. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 0. 1.]
  [1. 0. 1.]
  [1. 0. 1.]]]


## Test: SymmetryManager
Demonstrates example workflow, loading in an existing lattice from `lattice.npy`

In [11]:
from algorithm.Voxel import Voxel
from algorithm.Lattice import Lattice
from algorithm.Surroundings import SurroundingsManager
from algorithm.Symmetry import SymmetryManager

import numpy as np

print("SymmetryManager tests\n---\n")

input_lattice = np.load('lattice.npy')
print(f'Input lattice:\n{input_lattice}\n')

lattice = Lattice(input_lattice)
print(f'Min design:\n{lattice.MinDesign}\n')
print(f'Voxels:\n{lattice.voxels}\n')
print(f'Voxel indices:\n{[voxel.index for voxel in lattice.voxels]}\n')

surr_manager = SurroundingsManager(lattice)
print(f'Full surroundings:\n{surr_manager.FullSurroundings}\n')
print(f'VoxelSurroundings for voxel 0:\n{surr_manager.getVoxelSurroundings(lattice.voxels[0])}\n')
print(f'VoxelSurroundings for voxel 1:\n{surr_manager.getVoxelSurroundings(lattice.voxels[1])}\n')

sym_manager = SymmetryManager(lattice, surr_manager)
sym_manager.checkAllSymmetries()
df = sym_manager.getSymmetryDict_df()

SymmetryManager tests
---

Input lattice:
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[0. 1. 0.]
  [0. 1. 0.]]

 [[0. 1. 0.]
  [0. 1. 0.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]

Min design:
[[[1. 1.]]

 [[0. 1.]]

 [[0. 1.]]]

Voxels:
[<algorithm.Voxel.Voxel object at 0x16aa56870>, <algorithm.Voxel.Voxel object at 0x29cc4deb0>, <algorithm.Voxel.Voxel object at 0x29cc4eed0>, <algorithm.Voxel.Voxel object at 0x29cc4ec00>, <algorithm.Voxel.Voxel object at 0x29cc4df70>, <algorithm.Voxel.Voxel object at 0x29cc4cc50>]

Voxel indices:
[0, 1, 2, 3, 4, 5]

Full surroundings:
[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
  [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
  [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
  [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
  [0. 

In [1]:
# Tests 2
from algorithm.Voxel import Voxel
from algorithm.Lattice import Lattice
from algorithm.Surroundings import SurroundingsManager
from algorithm.Symmetry import SymmetryManager

import numpy as np
import pandas as pd

print("SymmetryManager tests\n---\n")

input_lattice = np.load('lattice.npy')
print(f'Input lattice:\n{input_lattice}\n')

lattice = Lattice(input_lattice)
print(f'Min design:\n{lattice.MinDesign}\n')
print(f'Voxels:\n{lattice.voxels}\n')
print(f'Voxel indices:\n{[voxel.index for voxel in lattice.voxels]}\n')

surr_manager = SurroundingsManager(lattice)
print(f'Full surroundings:\n{surr_manager.FullSurroundings}\n')
print(f'VoxelSurroundings for voxel 0:\n{surr_manager.getVoxelSurroundings(lattice.voxels[0])}\n')
print(f'VoxelSurroundings for voxel 1:\n{surr_manager.getVoxelSurroundings(lattice.voxels[1])}\n')

sym_manager = SymmetryManager(lattice, surr_manager)
sym_manager.checkAllSymmetries()
df = sym_manager.getSymmetryDict_df()

df

SymmetryManager tests
---

Input lattice:
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[0. 1. 0.]
  [0. 1. 0.]]

 [[0. 1. 0.]
  [0. 1. 0.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]

Min design:
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[0. 1. 0.]
  [0. 1. 0.]]

 [[0. 1. 0.]
  [0. 1. 0.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]

Voxels:
[<algorithm.Voxel.Voxel object at 0x10f4d9a30>, <algorithm.Voxel.Voxel object at 0x12e93a120>, <algorithm.Voxel.Voxel object at 0x11a091070>, <algorithm.Voxel.Voxel object at 0x11f30d9a0>, <algorithm.Voxel.Voxel object at 0x12e8e4470>, <algorithm.Voxel.Voxel object at 0x11dacc980>, <algorithm.Voxel.Voxel object at 0x11e9db380>, <algorithm.Voxel.Voxel object at 0x11e952a80>, <algorithm.Voxel.Voxel object at 0x11a0dff50>, <algorithm.Voxel.Voxel object at 0x109499a90>, <algorithm.Voxel.Voxel object at 0x109499250>, <algorithm.Voxel.Voxel object at 0x109499bb0>, <algorithm.Voxel.Voxel object at 0x1094998b0>, <algorithm.Voxel.Voxel object at 0x11a069640>, <algorithm.Voxel.Voxel object at 0x11a069340>, <algor

Voxel Pair  90° Rotation in x axis  180° Rotation in x axis  \
0         (0,)                   False                    False   
1       (1, 0)                   False                    False   
2       (0, 2)                   False                     True   
3       (3, 0)                   False                    False   
4       (0, 4)                   False                    False   
..         ...                     ...                      ...   
295   (21, 22)                   False                    False   
296   (21, 23)                   False                     True   
297      (22,)                   False                     True   
298   (22, 23)                   False                    False   
299      (23,)                   False                    False   

     270° Rotation in x axis  90° Rotation in y axis  180° Rotation in y axis  \
0                      False                   False                    False   
1                      False                   False                    False   
2                      False                   False                    False   
3                      False                   False                    False   
4                      False                   False                    False   
..                       ...                     ...                      ...   
295                    False                   False                    False   
296                    False                   False                    False   
297                    False                   False                    False   
298                    False                   False                    False   
299                    False                   False                    False   

     270° Rotation in y axis  90° Rotation in z axis  180° Rotation in z axis  \
0                      False                   False                    False   
1                      False                   False                    False   
2                      False                   False                    False   
3                      False                   False                    False   
4                      False                   False                    False   
..                       ...                     ...                      ...   
295                    False                   False                    False   
296                    False                   False                    False   
297                    False                   False                    False   
298                    False                   False                    False   
299                    False                   False                    False   

     270° Rotation in z axis  
0                      False  
1                      False  
2                      False  
3                      False  
4                      False  
..                       ...  
295                    False  
296                    False  
297                    False  
298                    False  
299                    False  

[300 rows x 10 columns]

In [2]:
df

Voxel Pair  90° Rotation in x axis  180° Rotation in x axis  \
0         (0,)                   False                    False   
1       (1, 0)                   False                    False   
2       (0, 2)                   False                     True   
3       (3, 0)                   False                    False   
4       (0, 4)                   False                    False   
..         ...                     ...                      ...   
295   (21, 22)                   False                    False   
296   (21, 23)                   False                     True   
297      (22,)                   False                     True   
298   (22, 23)                   False                    False   
299      (23,)                   False                    False   

     270° Rotation in x axis  90° Rotation in y axis  180° Rotation in y axis  \
0                      False                   False                    False   
1                      False                   False                    False   
2                      False                   False                    False   
3                      False                   False                    False   
4                      False                   False                    False   
..                       ...                     ...                      ...   
295                    False                   False                    False   
296                    False                   False                    False   
297                    False                   False                    False   
298                    False                   False                    False   
299                    False                   False                    False   

     270° Rotation in y axis  90° Rotation in z axis  180° Rotation in z axis  \
0                      False                   False                    False   
1                      False                   False                    False   
2                      False                   False                    False   
3                      False                   False                    False   
4                      False                   False                    False   
..                       ...                     ...                      ...   
295                    False                   False                    False   
296                    False                   False                    False   
297                    False                   False                    False   
298                    False                   False                    False   
299                    False                   False                    False   

     270° Rotation in z axis  
0                      False  
1                      False  
2                      False  
3                      False  
4                      False  
..                       ...  
295                    False  
296                    False  
297                    False  
298                    False  
299                    False  

[300 rows x 10 columns]