DNA Origami
---
Written by Sarah Hong, adapted from Jason Kahn

In [28]:
%%python

from visualizations.LatticeCreator import LatticeCreatorGUI
import os
import numpy as np

lc_gui = LatticeCreatorGUI()
lattice, isUnitCell = lc_gui.run()

print("The final lattice is:")
print(lattice)
print("Is it a unit cell? ", isUnitCell)

if lattice is not None:
    np.save("lattice.npy", lattice)

The final lattice is:
[[[1. 0. 1.]
  [0. 1. 0.]
  [1. 0. 1.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[1. 0. 1.]
  [0. 1. 0.]
  [1. 0. 1.]]]
Is it a unit cell?  1


In [29]:
import sys
import numpy as np
from vispy import app, scene
from vispy.color import Color
from visualizations.LatticeVisualizer import LatticeVisualizer

In [30]:
%gui qt

with open('lattice.npy', 'rb') as f:
    lattice = np.load(f)

print(lattice)

vis = LatticeVisualizer(lattice)
vis.run()

[[[1. 0. 1.]
  [0. 1. 0.]
  [1. 0. 1.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[1. 0. 1.]
  [0. 1. 0.]
  [1. 0. 1.]]]


In [31]:
from algorithm.Voxel import Voxel, Lattice, SurroundingsManager

input_lattice = np.load('lattice.npy')
lattice = Lattice(input_lattice)
SM = SurroundingsManager(lattice)

In [32]:
# %gui qt

# Visualize the UnitCell

# UC_vis = LatticeVisualizer(lattice.UnitCell)
# UC_vis.run()

In [33]:
%gui qt

# Visualize the MinDesign

MD_vis = LatticeVisualizer(lattice.MinDesign)
MD_vis.run()

In [34]:
# %gui qt

# Visualize the FullSurroundings 
# (Not recommended for large designs, it's extremely slow even for simple ones)

# FS_vis = LatticeVisualizer(SM.FullSurroundings)
# FS_vis.run()

print(f'FullSurroundings:\n{SM.FullSurroundings}')
print(f'Shape: {SM.FullSurroundings.shape}')

FullSurroundings:
[[[1. 0. 1. 0. 1. 0.]
  [0. 1. 0. 1. 0. 1.]
  [1. 0. 1. 0. 1. 0.]
  [0. 1. 0. 1. 0. 1.]
  [1. 0. 1. 0. 1. 0.]
  [0. 1. 0. 1. 0. 1.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[1. 0. 1. 0. 1. 0.]
  [0. 1. 0. 1. 0. 1.]
  [1. 0. 1. 0. 1. 0.]
  [0. 1. 0. 1. 0. 1.]
  [1. 0. 1. 0. 1. 0.]
  [0. 1. 0. 1. 0. 1.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[1. 0. 1. 0. 1. 0.]
  [0. 1. 0. 1. 0. 1.]
  [1. 0. 1. 0. 1. 0.]
  [0. 1. 0. 1. 0. 1.]
  [1. 0. 1. 0. 1. 0.]
  [0. 1. 0. 1. 0. 1.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]
Shape: (6, 6, 6)
