DNA Origami
---
Written by Sarah Hong, adapted from Jason Kahn

In [1]:
%%python
from LatticeCreator import LatticeCreatorGUI

import os
import numpy as np

lc_gui = LatticeCreatorGUI()
lattice, isUnitCell = lc_gui.run()

print("The final lattice is:")
print(lattice)
print("Is it a unit cell? ", isUnitCell)

if lattice is not None:
    np.save("lattice.npy", lattice)

The final lattice is:
[[[1. 0. 1.]
  [0. 1. 0.]
  [1. 0. 1.]]

 [[0. 2. 0.]
  [2. 4. 2.]
  [0. 2. 0.]]

 [[1. 0. 1.]
  [0. 1. 0.]
  [1. 0. 1.]]]
Is it a unit cell?  1


In [2]:
%gui qt

import sys
import numpy as np
from vispy import app, scene
from vispy.color import Color

from Visualizations import Visualizer

with open('lattice.npy', 'rb') as f:
    lattice = np.load(f)

print(lattice)

vis = Visualizer(lattice)
vis.run()

[[[1. 0. 1.]
  [0. 1. 0.]
  [1. 0. 1.]]

 [[0. 2. 0.]
  [2. 4. 2.]
  [0. 2. 0.]]

 [[1. 0. 1.]
  [0. 1. 0.]
  [1. 0. 1.]]]
