DNA Origami
---
Written by Sarah Hong, adapted from Jason Kahn

In [8]:
%%python
from LatticeCreator import LatticeCreatorGUI

import os
import numpy as np

lc_gui = LatticeCreatorGUI()
lattice, isUnitCell = lc_gui.run()

print("The final lattice is:")
print(lattice)
print("Is it a unit cell? ", isUnitCell)

np.save("lattice.npy", lattice)

The final lattice is:
[[[1. 4. 4.]
  [1. 2. 4.]
  [3. 0. 0.]]

 [[2. 1. 4.]
  [1. 2. 2.]
  [1. 0. 1.]]

 [[2. 2. 0.]
  [4. 1. 4.]
  [4. 0. 1.]]]
Is it a unit cell?  1


In [9]:
import numpy as np

with open('lattice.npy', 'rb') as f:
    lattice = np.load(f)

print(lattice)


[[[1. 4. 4.]
  [1. 2. 4.]
  [3. 0. 0.]]

 [[2. 1. 4.]
  [1. 2. 2.]
  [1. 0. 1.]]

 [[2. 2. 0.]
  [4. 1. 4.]
  [4. 0. 1.]]]
