DNA Origami
---
Written by Sarah Hong, adapted from Jason Kahn

In [1]:
%%python

from visualizations.LatticeCreator import LatticeCreatorGUI
import os
import numpy as np

lc_gui = LatticeCreatorGUI()
lattice, isUnitCell = lc_gui.run()

print("The final lattice is:")
print(lattice)
print("Is it a unit cell? ", isUnitCell)

if lattice is not None:
    np.save("lattice.npy", lattice)

The final lattice is:
[[[1. 2. 2.]
  [3. 0. 0.]
  [2. 0. 3.]]

 [[3. 1. 0.]
  [2. 4. 4.]
  [2. 1. 0.]]

 [[2. 3. 2.]
  [2. 3. 2.]
  [4. 1. 3.]]]
Is it a unit cell?  1


In [2]:
import sys
import numpy as np
from vispy import app, scene
from vispy.color import Color
from visualizations.LatticeVisualizer import LatticeVisualizer

In [3]:
%gui qt

with open('lattice.npy', 'rb') as f:
    lattice = np.load(f)

print(lattice)

vis = LatticeVisualizer(lattice)
vis.run()

[[[1. 2. 2.]
  [3. 0. 0.]
  [2. 0. 3.]]

 [[3. 1. 0.]
  [2. 4. 4.]
  [2. 1. 0.]]

 [[2. 3. 2.]
  [2. 3. 2.]
  [4. 1. 3.]]]


In [18]:
from algorithm.Voxel import Voxel
from algorithm.Lattice import Lattice
from algorithm.Surroundings import SurroundingsManager

input_lattice = np.load('lattice.npy')
lattice = Lattice(input_lattice)
sm = SurroundingsManager(lattice)

z_repeats: 3, x_repeats: 3, y_repeats: 3


In [ ]:
# %gui qt

# Visualize the UnitCell
# UC_vis = LatticeVisualizer(lattice.UnitCell)
# UC_vis.run()

# Visualize the MinDesign
# MD_vis = LatticeVisualizer(lattice.MinDesign)
# MD_vis.run()

In [ ]:
# %gui qt

# Visualize the FullSurroundings 
# (Not recommended for large designs, it's extremely slow even for simple ones)

# FS_vis = LatticeVisualizer(SM.FullSurroundings)
# FS_vis.run()

print(f'FullSurroundings:\n{sm.FullSurroundings}')
print(f'Shape: {sm.FullSurroundings.shape}')

FullSurroundings:
[[[1. 2. 2. 1. 2. 2. 1. 2. 2.]
  [3. 0. 0. 3. 0. 0. 3. 0. 0.]
  [2. 0. 3. 2. 0. 3. 2. 0. 3.]
  [1. 2. 2. 1. 2. 2. 1. 2. 2.]
  [3. 0. 0. 3. 0. 0. 3. 0. 0.]
  [2. 0. 3. 2. 0. 3. 2. 0. 3.]
  [1. 2. 2. 1. 2. 2. 1. 2. 2.]
  [3. 0. 0. 3. 0. 0. 3. 0. 0.]
  [2. 0. 3. 2. 0. 3. 2. 0. 3.]]

 [[3. 1. 0. 3. 1. 0. 3. 1. 0.]
  [2. 4. 4. 2. 4. 4. 2. 4. 4.]
  [2. 1. 0. 2. 1. 0. 2. 1. 0.]
  [3. 1. 0. 3. 1. 0. 3. 1. 0.]
  [2. 4. 4. 2. 4. 4. 2. 4. 4.]
  [2. 1. 0. 2. 1. 0. 2. 1. 0.]
  [3. 1. 0. 3. 1. 0. 3. 1. 0.]
  [2. 4. 4. 2. 4. 4. 2. 4. 4.]
  [2. 1. 0. 2. 1. 0. 2. 1. 0.]]

 [[2. 3. 2. 2. 3. 2. 2. 3. 2.]
  [2. 3. 2. 2. 3. 2. 2. 3. 2.]
  [4. 1. 3. 4. 1. 3. 4. 1. 3.]
  [2. 3. 2. 2. 3. 2. 2. 3. 2.]
  [2. 3. 2. 2. 3. 2. 2. 3. 2.]
  [4. 1. 3. 4. 1. 3. 4. 1. 3.]
  [2. 3. 2. 2. 3. 2. 2. 3. 2.]
  [2. 3. 2. 2. 3. 2. 2. 3. 2.]
  [4. 1. 3. 4. 1. 3. 4. 1. 3.]]

 [[1. 2. 2. 1. 2. 2. 1. 2. 2.]
  [3. 0. 0. 3. 0. 0. 3. 0. 0.]
  [2. 0. 3. 2. 0. 3. 2. 0. 3.]
  [1. 2. 2. 1. 2. 2. 1. 2. 2.]
  [3. 0. 0. 3. 

In [ ]:
%gui qt
# Get VoxelSurroundings for voxel at (0, 0, 0)

print(f'Original lattice: \n{lattice.MinDesign}\n')
voxel = lattice.voxels[0]
print(f'Voxel {voxel.index} has coordinates: {voxel.coordinates} in original lattice')

vox_surround = sm.getVoxelSurroundings(voxel)
VS_vis = LatticeVisualizer(vox_surround)
VS_vis.run()

print(f'Surrounding matrix for Voxel {voxel.index}:\n{vox_surround}')

Original lattice: 
[[[1. 2. 2.]
  [3. 0. 0.]
  [2. 0. 3.]]

 [[3. 1. 0.]
  [2. 4. 4.]
  [2. 1. 0.]]

 [[2. 3. 2.]
  [2. 3. 2.]
  [4. 1. 3.]]]

Voxel 0 has coordinates: (0, 0, 0) in original lattice
Surrounding matrix for Voxel 0:
[[[3. 4. 1.]
  [2. 2. 3.]
  [2. 2. 3.]]

 [[3. 2. 0.]
  [2. 1. 2.]
  [0. 3. 0.]]

 [[0. 2. 1.]
  [0. 3. 1.]
  [4. 2. 4.]]]
