DNA Origami
---
Written by Sarah Hong, adapted from Jason Kahn

In [10]:
%%python

from visualizations.LatticeCreator import LatticeCreatorGUI
import os
import numpy as np

lc_gui = LatticeCreatorGUI()
lattice, isUnitCell = lc_gui.run()

print("The final lattice is:")
print(lattice)
print("Is it a unit cell? ", isUnitCell)

if lattice is not None:
    np.save("lattice.npy", lattice)

The final lattice is:
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
Is it a unit cell?  1


In [11]:
import sys
import numpy as np
from vispy import app, scene
from vispy.color import Color
from visualizations.LatticeVisualizer import LatticeVisualizer

In [12]:
%gui qt

with open('lattice.npy', 'rb') as f:
    lattice = np.load(f)

print(lattice)

vis = LatticeVisualizer(lattice)
vis.run()

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [13]:
from algorithm.Voxel import Voxel, Lattice, SurroundingsManager

input_lattice = np.load('lattice.npy')
lattice = Lattice(input_lattice)
sm = SurroundingsManager(lattice)

z_repeats: 3, x_repeats: 5, y_repeats: 5


In [14]:
# %gui qt

# Visualize the UnitCell

# UC_vis = LatticeVisualizer(lattice.UnitCell)
# UC_vis.run()

In [15]:
%gui qt

# Visualize the MinDesign

# MD_vis = LatticeVisualizer(lattice.MinDesign)
# MD_vis.run()

In [16]:
# %gui qt

# Visualize the FullSurroundings 
# (Not recommended for large designs, it's extremely slow even for simple ones)

# FS_vis = LatticeVisualizer(SM.FullSurroundings)
# FS_vis.run()

print(f'FullSurroundings:\n{sm.FullSurroundings}')
print(f'Shape: {sm.FullSurroundings.shape}')

FullSurroundings:
[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.

In [18]:
%gui qt
# Get VoxelSurroundings for voxel at (0, 0, 0)

print(f'Original lattice: \n{lattice.MinDesign}\n')
voxel = lattice.voxels[0]
print(f'Voxel: {voxel}')
print(f'Voxel coordinates: {voxel.coordinates}')

vox_surround = sm.getVoxelSurroundings(voxel)
# VS_vis = LatticeVisualizer(vox_surround)
# VS_vis.run()
# print(sm.FullSurroundings)
print(vox_surround)
# print(np.shape(vox_surround))

Original lattice: 
[[[1. 1.]
  [1. 1.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]

Voxel: <algorithm.Voxel.Voxel object at 0x17fb25970>
Voxel coordinates: (0, 0, 0)
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
