DNA Origami
---
Written by Sarah Hong, adapted from Jason Kahn

In [ ]:
%%python
from LatticeCreator import LatticeCreatorGUI

import os
import numpy as np

lc_gui = LatticeCreatorGUI()
lattice, isUnitCell = lc_gui.run()

print("The final lattice is:")
print(lattice)
print("Is it a unit cell? ", isUnitCell)

np.save("lattice.npy", lattice)

In [19]:
import sys
import numpy as np
from vispy import app, scene
from vispy.color import Color

with open('lattice.npy', 'rb') as f:
    lattice = np.load(f)

print(lattice)
nlay, nrow, ncol = lattice.shape

canvas = scene.SceneCanvas(keys='interactive', size=(800, 600), show=True)

view = canvas.central_widget.add_view()
view.bgcolor = '#efefef'
view.camera = scene.cameras.ArcballCamera(fov=0)
view.camera.scale_factor = 500

# Define a color dictionary
colordict = {
    0: Color("#AAAAAA80"),  # Transparent grey color
}

# Generate random colors for other values
for i in range(1, 73):  # Values 1 to 72
    color = Color((np.random.rand(), np.random.rand(), np.random.rand()))
    color.alpha = 1.0  # Set the alpha value separately
    colordict[i] = color

coords = []
colors = []

dist = 40

for i in range(nlay):
    for j in range(nrow):
        for k in range(ncol):
            # Calculate position for the particle
            x, y, z = i*dist, j*dist, k*dist # Each particle (dist) away from each other

            color = colordict[lattice[i, j, k]]  # Get associated color
            colors.append(color.rgba)
            
            coords.append((x, y, z))


coords = np.concatenate([coords, [[0, 0, 0]]], axis=0)
colors = np.concatenate([colors, [[1, 0, 0, 1]]] * (len(coords) - len(colors)), axis=0)

vis = scene.visuals.Markers(
    pos = coords,
    size = 20,
    antialias=0,
    face_color=colors,
    edge_color='white',
    edge_width=0,
    scaling=True,
    spherical=True
)

vis.parent = view.scene

# ambient_light = scene.LightAmbient(intensity=0.5)
# view.add(ambient_light)

if __name__ == '__main__':
    app.run()

[[[4. 4. 1.]
  [3. 2. 0.]
  [3. 3. 2.]]

 [[1. 4. 0.]
  [4. 4. 3.]
  [4. 2. 3.]]

 [[1. 1. 1.]
  [3. 4. 0.]
  [0. 2. 2.]]]
