DNA Origami
---
Written by Sarah Hong, adapted from Jason Kahn

In [5]:
%%python
from LatticeCreator import LatticeCreatorGUI

import os
import numpy as np

lc_gui = LatticeCreatorGUI()
lattice, isUnitCell = lc_gui.run()

print("The final lattice is:")
print(lattice)
print("Is it a unit cell? ", isUnitCell)

if lattice is not None:
    np.save("lattice.npy", lattice)

The final lattice is:
[[[1. 0. 1.]
  [0. 1. 0.]
  [1. 0. 1.]]

 [[2. 0. 2.]
  [0. 3. 0.]
  [2. 0. 2.]]

 [[4. 0. 4.]
  [0. 4. 0.]
  [4. 0. 4.]]]
Is it a unit cell?  1


In [6]:
%gui qt

import sys
import numpy as np
from vispy import app, scene
from vispy.color import Color

from Visualizations import Visualizer

with open('lattice.npy', 'rb') as f:
    lattice = np.load(f)

print(lattice)

vis = Visualizer(lattice)
vis.run()

[[[1. 0. 1.]
  [0. 1. 0.]
  [1. 0. 1.]]

 [[2. 0. 2.]
  [0. 3. 0.]
  [2. 0. 2.]]

 [[4. 0. 4.]
  [0. 4. 0.]
  [4. 0. 4.]]]
Voxel at (0, 0, 0) has color [0.21568628 0.5058824  0.6627451  1.        ]
Voxel at (0, 0, 40) has color [0.6666667 0.6666667 0.6666667 0.5019608]
Voxel at (0, 0, 80) has color [0.21568628 0.5058824  0.6627451  1.        ]
Voxel at (0, 40, 0) has color [0.6666667 0.6666667 0.6666667 0.5019608]
Voxel at (0, 40, 40) has color [0.21568628 0.5058824  0.6627451  1.        ]
Voxel at (0, 40, 80) has color [0.6666667 0.6666667 0.6666667 0.5019608]
Voxel at (0, 80, 0) has color [0.21568628 0.5058824  0.6627451  1.        ]
Voxel at (0, 80, 40) has color [0.6666667 0.6666667 0.6666667 0.5019608]
Voxel at (0, 80, 80) has color [0.21568628 0.5058824  0.6627451  1.        ]
Voxel at (40, 0, 0) has color [0.34117648 0.6745098  0.75686276 1.        ]
Voxel at (40, 0, 40) has color [0.6666667 0.6666667 0.6666667 0.5019608]
Voxel at (40, 0, 80) has color [0.34117648 0.6745098  0.7