DNA Origami
---
Written by Sarah Hong, adapted from Jason Kahn

In [ ]:
%%python
from LatticeCreator import LatticeCreatorGUI

import os
import numpy as np

lc_gui = LatticeCreatorGUI()
lattice, isUnitCell = lc_gui.run()

print("The final lattice is:")
print(lattice)
print("Is it a unit cell? ", isUnitCell)

np.save("lattice.npy", lattice)

In [1]:
%gui qt

import sys
import numpy as np
from vispy import app, scene
from vispy.color import Color

from Visualizations import Visualizer

with open('lattice.npy', 'rb') as f:
    lattice = np.load(f)

print(lattice)

vis = Visualizer(lattice)
vis.run()

[[[2. 2. 4.]
  [1. 0. 3.]
  [2. 1. 4.]]

 [[1. 1. 2.]
  [3. 2. 3.]
  [3. 2. 0.]]

 [[4. 2. 2.]
  [0. 4. 0.]
  [3. 2. 4.]]]
