# App Flow Examples
This notebook demonstrates how to interactively create and visualize voxel-bond lattice structures in Jupyter notebooks.

### Warnings on running PyQt6 / pyqtgraph applications in Jupyter

Because PyQt6 is not optimized for running in Jupyter environments, you may potentially crash the Jupyter kernel if you:

- Rerun notebook cells without closing the existing program
- Try to open / close a GUI instance too many times in a very short timespan

The `if-else` statements were added to the app-flow to hopefully catch any existing PyQt application instances and limit the frequency of such events. In the case of any crashes/errors, try restarting your kernel and rerunning the notebook.

### Shaders are disabled in Jupyter

Note that shaders are also disabled in a Jupyter runtime environment (due to a bug in pyqtgraph which has remained unfixed for at least 10 years). If you are experiencing continuing frustration, or want nicer shaded graphics, run the program from `/main.py` instead.

In [ ]:
# This cell allows modules to be reloaded automatically when they are changed
%load_ext autoreload
%autoreload 2

## RunDesigner
Runs a GUI which allows you to quickly create 3D numpy arrays which can be used as inputs for the coloring algorithm and for lattice visualization.

Your created lattice should be stored in `lattice`, as the return value of RunDesigner.

In [1]:
%gui qt

import sys
from PyQt6.QtWidgets import QApplication
from PyQt6.QtCore import QCoreApplication

sys.path.append('../')
from app.design.Designer import RunDesigner

if __name__ == '__main__':
    if not QCoreApplication.instance():
        app = QApplication(sys.argv)
    else:
        app = QCoreApplication.instance()
    
    designer = RunDesigner(app)
    lattice = designer.run()
    
    if lattice is not None:
        print(f'Lattice received.')
    else:
        print("No lattice received.")

No lattice received.


## RunVisualizer
Once you have your numpy array, create a Lattice object with it.

RunVisualizer accepts this Lattice object as an input, and visualizes the different integer values of the array as the voxel 'colors'. A typical workflow would be to use the `lattice` output of RunDesigner as the input parameter for RunVisualizer.

This example loads a sample numpy array from a file `data/lattice.npy`. 

In [3]:
%gui qt

import sys
import numpy as np
from PyQt6.QtWidgets import QApplication
from PyQt6.QtCore import QCoreApplication

sys.path.append('../')
from app.visualize.Visualizer import RunVisualizer
from algorithm.Lattice import Lattice

if __name__ == '__main__':
    if not QCoreApplication.instance():
        app = QApplication(sys.argv)
    else:
        app = QCoreApplication.instance()

    # Load the input lattice
    input_lattice = np.load('data/lattice.npy')
    print(f'Visualizing lattice:\n{input_lattice}\n')
    lattice = Lattice(input_lattice)

    visualizeWindow = RunVisualizer(lattice, app)

Visualizing lattice:
[[[1 1]
  [1 1]]

 [[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]

