# Painting Tests

In [3]:
%load_ext autoreload
%autoreload 2

In [4]:
import sys

sys.path.append('../')
from algorithm.Voxel import Voxel
from algorithm.Lattice import Lattice
from algorithm.Surroundings import SurroundingsManager
from algorithm.SymmetryDf import SymmetryDf
from algorithm.BondPainter import Mesovoxel, BondPainter

import numpy as np
import pandas as pd

## Setup: View the lattice

In [87]:
%gui qt

import sys
from PyQt6.QtWidgets import QApplication
from PyQt6.QtCore import QCoreApplication

sys.path.append('../')
from app.design.Designer import RunDesigner

if __name__ == '__main__':
    if not QCoreApplication.instance():
        app = QApplication(sys.argv)
    else:
        app = QCoreApplication.instance()
    
    designer = RunDesigner(app)
    input_lattice = designer.run()
    
    if input_lattice is not None:
        print(f'Lattice received.')
        np.save("data/lattice.npy", input_lattice)
    else:
        print("No lattice received.")

Saved lattice:
[[[1 1]
  [1 1]]

 [[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]

Lattice received.


In [88]:
%gui qt

import sys
import numpy as np
from PyQt6.QtWidgets import QApplication
from PyQt6.QtCore import QCoreApplication

sys.path.append('../')
from app.visualize.Visualizer import RunVisualizer

if __name__ == '__main__':
    if not QCoreApplication.instance():
        app = QApplication(sys.argv)
    else:
        app = QCoreApplication.instance()

    # Load the input lattice
    input_lattice = np.load('data/lattice.npy')
    lattice = Lattice(input_lattice)
    print(f'Visualizing UnitCell:\n{lattice.UnitCell}\n')

    visualizeWindow = RunVisualizer(lattice, app)

Visualizing UnitCell:
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]



### Setup: Initialize symmetry data structures

In [58]:
input_lattice = np.load('data/lattice.npy')
# print(f'Input lattice:\n{input_lattice}\n')

lattice = Lattice(input_lattice)
surr_manager = SurroundingsManager(lattice)
symmetry_df = SymmetryDf(lattice, surr_manager)
df = symmetry_df.symmetry_df

df

translation 90° X-axis 180° X-axis 270° X-axis 90° Y-axis  \
(2, 8)         False      False       False       False      False   
(2, 3)          True      False       False       False      False   
(10, 13)       False      False       False       False      False   
(7, 8)         False      False        True       False      False   
(7, 14)        False      False       False       False      False   
...              ...        ...         ...         ...        ...   
(5, 14)        False      False       False       False      False   
(12, 15)        True      False       False       False      False   
(3, 10)        False      False       False       False      False   
(7)             True      False       False       False      False   
(10, 14)       False      False       False       False      False   

         180° Y-axis 270° Y-axis 90° Z-axis 180° Z-axis 270° Z-axis  ...  \
(2, 8)         False       False      False       False       False  ...   
(2, 3)         False       False       True        True        True  ...   
(10, 13)       False       False      False       False       False  ...   
(7, 8)          True       False      False       False       False  ...   
(7, 14)        False       False      False       False       False  ...   
...              ...         ...        ...         ...         ...  ...   
(5, 14)        False       False      False       False       False  ...   
(12, 15)       False       False       True        True        True  ...   
(3, 10)        False       False      False       False       False  ...   
(7)            False       False       True        True        True  ...   
(10, 14)       False       False      False       False       False  ...   

         90° X-axis + 270° Y-axis 90° X-axis + 270° Z-axis  \
(2, 8)                      False                    False   
(2, 3)                      False                    False   
(10, 13)                    False                    False   
(7, 8)                      False                    False   
(7, 14)                     False                    False   
...                           ...                      ...   
(5, 14)                     False                    False   
(12, 15)                    False                    False   
(3, 10)                     False                    False   
(7)                         False                    False   
(10, 14)                    False                    False   

         90° X-axis + 90° Z-axis 90° Y-axis + 180° X-axis  \
(2, 8)                     False                    False   
(2, 3)                     False                    False   
(10, 13)                   False                    False   
(7, 8)                     False                    False   
(7, 14)                    False                    False   
...                          ...                      ...   
(5, 14)                    False                    False   
(12, 15)                   False                    False   
(3, 10)                    False                    False   
(7)                        False                    False   
(10, 14)                   False                    False   

         90° Y-axis + 180° Z-axis 90° Y-axis + 270° X-axis  \
(2, 8)                      False                    False   
(2, 3)                      False                    False   
(10, 13)                    False                    False   
(7, 8)                      False                    False   
(7, 14)                     False                    False   
...                           ...                      ...   
(5, 14)                     False                    False   
(12, 15)                    False                    False   
(3, 10)                     False                    False   
(7)                         False                    False   
(10, 14)                    False                    False   

         90° Y-axis + 270° Z-axi

## Mesovoxel initialization tests
### 1. Structural / Complementary voxels

In [61]:
mesovoxel = Mesovoxel(lattice, symmetry_df)

print(f'Structural voxels\n---')
for voxel in mesovoxel.structural_voxels:
    print(f'Voxel {voxel.id} | Coordinates: {voxel.coordinates} Material: {voxel.material}')

print(f'\nComplementary voxels\n---')
for voxel in mesovoxel.complementary_voxels:
    print(f'Voxel {voxel.id} | Coordinates: {voxel.coordinates} Material: {voxel.material}')

Adding voxel 1 to complementary_voxels
---
Has the following symmetries with voxel 0:
['translation', '90° Z-axis', '180° Z-axis', '270° Z-axis', '180° X-axis + 180° Y-axis']

Adding voxel 2 to complementary_voxels
---
Has the following symmetries with voxel 0:
['translation', '90° Z-axis', '180° Z-axis', '270° Z-axis', '180° X-axis + 180° Y-axis']

Adding voxel 3 to complementary_voxels
---
Has the following symmetries with voxel 0:
['translation', '90° Z-axis', '180° Z-axis', '270° Z-axis', '180° X-axis + 180° Y-axis']

Adding voxel 5 to complementary_voxels
---
Has the following symmetries with voxel 4:
['translation', '90° Z-axis', '180° Z-axis', '270° Z-axis', '180° X-axis + 180° Y-axis']

Adding voxel 6 to complementary_voxels
---
Has the following symmetries with voxel 4:
['translation', '90° Z-axis', '180° Z-axis', '270° Z-axis', '180° X-axis + 180° Y-axis']

Adding voxel 7 to complementary_voxels
---
Has the following symmetries with voxel 4:
['translation', '90° Z-axis', '180

### 2. Paint all bonds between structural voxels

In [62]:
bond_painter = BondPainter(lattice, surr_manager, symmetry_df)
bond_painter.paint_mesovoxel(mesovoxel)

Paint bond with color (1):
Between voxel 0 ((0, 0, -1)) and voxel 4 ((0, 0, 1))



### Visualize the painted mesovoxel

In [65]:
%gui qt

import sys
import numpy as np
from PyQt6.QtWidgets import QApplication
from PyQt6.QtCore import QCoreApplication

sys.path.append('../')
from app.visualize.Visualizer import RunVisualizer

if __name__ == '__main__':
    if not QCoreApplication.instance():
        app = QApplication(sys.argv)
    else:
        app = QCoreApplication.instance()

    print(f'Visualizing MinDesign:\n{lattice.MinDesign}\n')
    visualizeWindow = RunVisualizer(bond_painter.lattice, app)

Visualizing MinDesign:
[[[1 1]
  [1 1]]

 [[0 0]
  [0 0]]

 [[0 0]
  [0 0]]

 [[1 1]
  [1 1]]]



## Rotate voxel tests

In [44]:
voxel = bond_painter.lattice.get_voxel(0)

print(symmetry_df.symlist(0, 0))

for direction, bond in voxel.bonds.items():
    print(f'Bond direction: {direction}, color: {bond.color}, type: {bond.type}')

['translation', '90° Z-axis', '180° Z-axis', '270° Z-axis', '180° X-axis + 180° Y-axis']
Bond direction: (1, 0, 0), color: None, type: None
Bond direction: (-1, 0, 0), color: None, type: None
Bond direction: (0, 1, 0), color: None, type: None
Bond direction: (0, -1, 0), color: None, type: None
Bond direction: (0, 0, 1), color: None, type: None
Bond direction: (0, 0, -1), color: 1, type: structural


In [45]:
from algorithm.RotationDict import VoxelRotater, NpRotationDict, ScipyRotationDict
from algorithm.Bond import Bond
from algorithm.Voxel import Voxel

scirot_dict = ScipyRotationDict()
rot = scirot_dict.get_rotation('90° Z-axis')

for _, bond in voxel.bonds.items():
    direction = np.array(bond.direction)
    rotated_direction = tuple(np.round(rot(direction)).astype(int))
    print(f'Original direction: {tuple(direction)}, rotated direction: {rotated_direction}')


rotater = VoxelRotater()
rotated_voxel = rotater.rotate_voxel(voxel, '180° X-axis + 180° Y-axis')

print("\nRotated voxel bonds:\n---")
for bond in rotated_voxel.bonds.values():
    print(f'Bond direction: {bond.direction}, color: {bond.color}, type: {bond.type}')


Original direction: (1, 0, 0), rotated direction: (0, 1, 0)
Original direction: (-1, 0, 0), rotated direction: (0, -1, 0)
Original direction: (0, 1, 0), rotated direction: (-1, 0, 0)
Original direction: (0, -1, 0), rotated direction: (1, 0, 0)
Original direction: (0, 0, 1), rotated direction: (0, 0, 1)
Original direction: (0, 0, -1), rotated direction: (0, 0, -1)

Rotated voxel bonds:
---
Bond direction: (-1, 0, 0), color: None, type: None
Bond direction: (1, 0, 0), color: None, type: None
Bond direction: (0, -1, 0), color: None, type: None
Bond direction: (0, 1, 0), color: None, type: None
Bond direction: (0, 0, 1), color: None, type: None
Bond direction: (0, 0, -1), color: 1, type: structural


## Self symmetry painting

In [ ]:
bond_painter.paint_self_symmetries(mesovoxel)

In [ ]:
bond_painter.main_loop(mesovoxel)

## Testing the full painting algorithm

In [54]:
input_lattice = np.load('data/lattice.npy')

lattice = Lattice(input_lattice)
surr_manager = SurroundingsManager(lattice)
symmetry_df = SymmetryDf(lattice, surr_manager)

# Bond painter stuff
bond_painter = BondPainter(lattice, surr_manager, symmetry_df)
mesovoxel = Mesovoxel(lattice, symmetry_df)

bond_painter.paint_mesovoxel(mesovoxel)
bond_painter.paint_all_self_symmetries(mesovoxel)
bond_painter.main_loop(mesovoxel)

Paint bond with color (1):
Between voxel 0 ((0, 0, -1)) and voxel 4 ((0, 0, 1))

(self)MapPainting voxel 0 with symmetry operation 180° X-axis
MapPaint: parent_voxel 0 --> 0 with symmetry operation 180° X-axis
(self)MapPainting voxel 0 with symmetry operation 180° Y-axis
MapPaint: parent_voxel 0 --> 0 with symmetry operation 180° Y-axis
(self)MapPainting voxel 0 with symmetry operation 90° Z-axis
MapPaint: parent_voxel 0 --> 0 with symmetry operation 90° Z-axis
(self)MapPainting voxel 0 with symmetry operation 180° Z-axis
MapPaint: parent_voxel 0 --> 0 with symmetry operation 180° Z-axis
(self)MapPainting voxel 0 with symmetry operation 270° Z-axis
MapPaint: parent_voxel 0 --> 0 with symmetry operation 270° Z-axis
(self)MapPainting voxel 0 with symmetry operation 180° X-axis + 180° Z-axis
MapPaint: parent_voxel 0 --> 0 with symmetry operation 180° X-axis + 180° Z-axis
(self)MapPainting voxel 0 with symmetry operation 180° X-axis + 90° Z-axis
MapPaint: parent_voxel 0 --> 0 with symmetry

In [59]:
%gui qt

import sys
import numpy as np
from PyQt6.QtWidgets import QApplication
from PyQt6.QtCore import QCoreApplication

sys.path.append('../')
from app.visualize.Visualizer import RunVisualizer

if __name__ == '__main__':
    if not QCoreApplication.instance():
        app = QApplication(sys.argv)
    else:
        app = QCoreApplication.instance()

    print(f'Visualizing MinDesign:\n{lattice.MinDesign}\n')
    visualizeWindow = RunVisualizer(bond_painter.lattice, app)

Visualizing MinDesign:
[[[1 1]
  [1 1]]

 [[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]



In [30]:
# Lists to store combined voxel and bond information
final_df = []

# Iterate through the voxels and bonds
for voxel in bond_painter.lattice.voxel_list:
    for direction, bond in voxel.bonds.items():
        final_df.append({
            'Voxel ID': voxel.id,
            'Coordinates': voxel.coordinates,
            'Material': voxel.material,
            'Bond Direction': direction,
            'Bond Color': bond.color,
            'Bond Type': bond.type
        })

# Create a DataFrame from the combined list
final_df = pd.DataFrame(final_df)
final_df

Voxel ID Coordinates  Material Bond Direction  Bond Color   Bond Type
0          0   (0, 1, 2)         1      (1, 0, 0)         2.0  structural
1          0   (0, 1, 2)         1     (-1, 0, 0)        -2.0      mapped
2          0   (0, 1, 2)         1      (0, 1, 0)         3.0  structural
3          0   (0, 1, 2)         1     (0, -1, 0)        -3.0      mapped
4          0   (0, 1, 2)         1      (0, 0, 1)         4.0  structural
..       ...         ...       ...            ...         ...         ...
67        11   (1, 0, 0)         0     (-1, 0, 0)         NaN        None
68        11   (1, 0, 0)         0      (0, 1, 0)         NaN        None
69        11   (1, 0, 0)         0     (0, -1, 0)         NaN        None
70        11   (1, 0, 0)         0      (0, 0, 1)         NaN        None
71        11   (1, 0, 0)         0     (0, 0, -1)        -4.0      mapped

[72 rows x 6 columns]

In [74]:
symdict = symmetry_df.partner_symdict(1)
for key, value in symdict.items():
    print(f'Voxel {key} | Symmetries: {value}')

Voxel 0 | Symmetries: ['translation', '90° Z-axis', '180° Z-axis', '270° Z-axis', '180° X-axis + 180° Y-axis']
Voxel 1 | Symmetries: ['translation', '90° Z-axis', '180° Z-axis', '270° Z-axis', '180° X-axis + 180° Y-axis']
Voxel 2 | Symmetries: ['translation', '90° Z-axis', '180° Z-axis', '270° Z-axis', '180° X-axis + 180° Y-axis']
Voxel 3 | Symmetries: ['translation', '90° Z-axis', '180° Z-axis', '270° Z-axis', '180° X-axis + 180° Y-axis']
Voxel 12 | Symmetries: ['180° X-axis', '180° Y-axis', '180° X-axis + 270° Z-axis', '180° X-axis + 90° Z-axis', '180° Y-axis + 270° Z-axis', '180° Y-axis + 90° Z-axis', '180° Z-axis + 180° X-axis', '180° Z-axis + 180° Y-axis']
Voxel 13 | Symmetries: ['180° X-axis', '180° Y-axis', '180° X-axis + 270° Z-axis', '180° X-axis + 90° Z-axis', '180° Y-axis + 270° Z-axis', '180° Y-axis + 90° Z-axis', '180° Z-axis + 180° X-axis', '180° Z-axis + 180° Y-axis']
Voxel 14 | Symmetries: ['180° X-axis', '180° Y-axis', '180° X-axis + 270° Z-axis', '180° X-axis + 90° Z-