# Symmetry Tests

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys

sys.path.append('../')
from algorithm.Voxel import Voxel
from algorithm.Lattice import Lattice
from algorithm.Surroundings import SurroundingsManager
from algorithm.Symmetry import SymmetryDf
from algorithm.BondPainter import Mesovoxel, BondPainter

import numpy as np
import pandas as pd

In [3]:
#TODO: Create MinDesign which displays Voxel.index for each location
print("SymmetryDf tests\n---\n")

input_lattice = np.load('data/lattice.npy')
print(f'Input lattice:\n{input_lattice}\n')

lattice = Lattice(input_lattice)

# Print statements
print(f'Min design:\n{lattice.MinDesign}\n')
print(f'voxel_list:\n{lattice.voxel_list}\n')

voxel_indices = [str(voxel.index) for voxel in lattice.voxel_list]
print(f'voxel_list indices:\n{", ".join(voxel_indices)}\n')

print(f'coord_list:\n{lattice.coord_list}\n')

surr_manager = SurroundingsManager(lattice)
# print(f'Full surroundings:\n{surr_manager.FullSurroundings}\n')
# print(f'VoxelSurroundings for voxel 0:\n{surr_manager.getVoxelSurroundings(lattice.voxels[0])}\n')
# print(f'VoxelSurroundings for voxel 1:\n{surr_manager.getVoxelSurroundings(lattice.voxels[1])}\n')

symmetry_df = SymmetryDf(lattice, surr_manager)
symmetry_df.compute_all_symmetries()
df = symmetry_df.symmetry_df
df

SymmetryDf tests
---

Input lattice:
[[[1. 1. 1.]
  [1. 0. 1.]
  [1. 1. 1.]]

 [[0. 0. 0.]
  [0. 1. 0.]
  [0. 0. 0.]]

 [[1. 1. 1.]
  [1. 0. 1.]
  [1. 1. 1.]]]

Min design:
[[[1. 1.]
  [1. 0.]]

 [[0. 0.]
  [0. 1.]]]

voxel_list:
[<algorithm.Voxel.Voxel object at 0x110d55010>, <algorithm.Voxel.Voxel object at 0x106bd7ef0>, <algorithm.Voxel.Voxel object at 0x1133961b0>, <algorithm.Voxel.Voxel object at 0x113394ef0>, <algorithm.Voxel.Voxel object at 0x113394b90>, <algorithm.Voxel.Voxel object at 0x113394e60>, <algorithm.Voxel.Voxel object at 0x1133954c0>, <algorithm.Voxel.Voxel object at 0x1133959a0>]

voxel_list indices:
0, 1, 2, 3, 4, 5, 6, 7

coord_list:
[(0, 1, 1), (1, 1, 1), (0, 0, 1), (1, 0, 1), (0, 1, 0), (1, 1, 0), (0, 0, 0), (1, 0, 0)]



translation 90° X-axis 180° X-axis 270° X-axis 90° Y-axis 180° Y-axis  \
(1, 4)       False      False       False       False      False       False   
(4, 6)       False      False       False       False      False       False   
(2, 3)       False      False       False       False      False       False   
(2, 6)       False      False       False       False      False       False   
(4, 5)       False      False       False       False      False       False   
(0, 5)       False      False       False       False      False       False   
(1)           True      False        True       False      False        True   
(3, 4)       False      False       False       False      False       False   
(0, 6)       False      False       False       False      False       False   
(1, 7)       False      False       False       False      False       False   
(0, 3)       False      False       False       False      False       False   
(2)           True      False        True       False      False        True   
(0, 2)       False      False       False       False      False       False   
(4)           True      False        True       False      False        True   
(0, 4)       False      False       False       False      False       False   
(2, 4)       False      False       False       False      False       False   
(5, 6)       False      False       False       False      False       False   
(3, 5)       False      False       False       False      False       False   
(1, 6)       False      False       False       False      False       False   
(0, 7)       False      False       False       False      False       False   
(1, 3)       False      False       False       False      False       False   
(4, 7)       False      False       False       False      False       False   
(3, 7)       False      False       False       False      False       False   
(0, 1)       False      False       False       False      False       False   
(3, 6)       False      False       False       False      False       False   
(6, 7)       False      False       False       False      False       False   
(5)           True      False        True       False      False        True   
(1, 5)       False      False       False       False      False       False   
(7)           True      False        True       False      False        True   
(2, 7)       False      False       False       False      False       False   
(5, 7)       False      False       False       False      False       False   
(1, 2)       False      False       False       False      False       False   
(2, 5)       False      False       False       False      False       False   
(3)           True      False        True       False      False        True   
(6)           True      False        True       False      False        True   
(0)           True      False        True       False      False        True   

       270° Y-axis 90° Z-axis 180° Z-axis 270° Z-axis  ...  \
(1, 4)       False      False       False       False  ...   
(4, 6)       False      False       False       False  ...   
(2, 3)       False      False       False       False  ...   
(2, 6)       False      False       False       False  ...   
(4, 5)       False      False       False       False  ...   
(0, 5)       False      False       False       False  ...   
(1)          False      False        True       False  ...   
(3, 4)       False      False       False       False  ...   
(0, 6)       False      False       False       False  ...   
(1, 7)       False      False       False       False  ...   
(0, 3)       False      False       False       False  ...   
(2)          False      False        True       False  ...   
(0, 2)       False      False       False       False  ...   
(4)          False       True        True        True  ...   
(0, 4)       False      False       False       False  ...   
(2, 4)       False      False       False       False 

## View SymDict for each voxel in MinDesign

In [62]:
symmetry_df.print_all_symdicts()

Voxel 0
---
Coordinates: (0, 1, 1) Material: 1.0
Symmetries:
(0): ['translation', '180° X-axis', '180° Y-axis', '90° Z-axis', '180° Z-axis', '270° Z-axis', '180° X-axis + 180° Y-axis', '180° X-axis + 180° Z-axis', '180° X-axis + 270° Z-axis', '180° X-axis + 90° Z-axis', '180° Z-axis + 180° Y-axis', '270° Z-axis + 180° Y-axis', '90° Z-axis + 180° Y-axis']


Voxel 1
---
Coordinates: (1, 1, 1) Material: 1.0
Symmetries:
(1): ['translation', '180° X-axis', '180° Y-axis', '180° Z-axis', '180° X-axis + 180° Y-axis', '180° X-axis + 180° Z-axis', '180° Z-axis + 180° Y-axis']
(1, 2): ['90° Z-axis', '270° Z-axis', '180° X-axis + 270° Z-axis', '180° X-axis + 90° Z-axis', '270° Z-axis + 180° Y-axis', '90° Z-axis + 180° Y-axis']


Voxel 2
---
Coordinates: (0, 0, 1) Material: 1.0
Symmetries:
(1, 2): ['90° Z-axis', '270° Z-axis', '180° X-axis + 270° Z-axis', '180° X-axis + 90° Z-axis', '270° Z-axis + 180° Y-axis', '90° Z-axis + 180° Y-axis']
(2): ['translation', '180° X-axis', '180° Y-axis', '180° Z-a

## Test: Inspect the lattice design

In [6]:
%gui qt

import sys
import numpy as np
from PyQt6.QtWidgets import QApplication
from PyQt6.QtCore import QCoreApplication

sys.path.append('../')
from app.visualize.Visualizer import RunVisualizer

if __name__ == '__main__':
    if not QCoreApplication.instance():
        app = QApplication(sys.argv)
    else:
        app = QCoreApplication.instance()

    # Load the input lattice
    input_lattice = np.load('data/lattice.npy')
    lattice = Lattice(input_lattice)
    print(f'Visualizing MinDesign:\n{lattice.MinDesign}\n')

    visualizeWindow = RunVisualizer(lattice.UnitCell, app)

Visualizing MinDesign:
[[[1. 1.]
  [1. 0.]]

 [[0. 0.]
  [0. 1.]]]



# Mesovoxel initialization tests

In [63]:
mesovoxel = Mesovoxel(lattice, symmetry_df)

voxel1_partner_symdict = symmetry_df.partner_symdict(1)

print(f'Voxel 1 partner_symdict:')
for key, value in voxel1_partner_symdict.items():
    print(f'{key}: {value}')

print(f'\nStructural voxels\n---')
for voxel in mesovoxel.structural_voxels:
    print(f'Voxel {voxel.index} Coordinates: {voxel.coordinates} Material: {voxel.material}')

print(f'\nComplementary voxels\n---')
for voxel in mesovoxel.complementary_voxels:
    print(f'Voxel {voxel.index} Coordinates: {voxel.coordinates} Material: {voxel.material}')

Adding voxel 2 to complementary_voxels
---
Has the following symmetries with voxel 1:
['90° Z-axis', '270° Z-axis', '180° X-axis + 270° Z-axis', '180° X-axis + 90° Z-axis', '270° Z-axis + 180° Y-axis', '90° Z-axis + 180° Y-axis']

Adding voxel 6 to complementary_voxels
---
Has the following symmetries with voxel 5:
['90° Z-axis', '270° Z-axis', '180° X-axis + 270° Z-axis', '180° X-axis + 90° Z-axis', '270° Z-axis + 180° Y-axis', '90° Z-axis + 180° Y-axis']

Voxel 1 partner_symdict:
1: ['translation', '180° X-axis', '180° Y-axis', '180° Z-axis', '180° X-axis + 180° Y-axis', '180° X-axis + 180° Z-axis', '180° Z-axis + 180° Y-axis']
2: ['90° Z-axis', '270° Z-axis', '180° X-axis + 270° Z-axis', '180° X-axis + 90° Z-axis', '270° Z-axis + 180° Y-axis', '90° Z-axis + 180° Y-axis']

Structural voxels
---
Voxel 0 Coordinates: (0, 1, 1) Material: 1.0
Voxel 1 Coordinates: (1, 1, 1) Material: 1.0
Voxel 3 Coordinates: (1, 0, 1) Material: 0.0
Voxel 4 Coordinates: (0, 1, 0) Material: 0.0
Voxel 5 Coor

# Test some painting

In [64]:
#TODO: Be able to visualize bond painting
bond_painter = BondPainter(lattice, surr_manager, symmetry_df)
bond_painter.paint_mesovoxel(mesovoxel)

Paint bond with color (1):
Between voxel 0 (+x) and voxel 1 (-x)

Paint bond with color (2):
Between voxel 0 (-x) and voxel 1 (+x)

Paint bond with color (3):
Between voxel 0 (+z) and voxel 4 (-z)

Paint bond with color (4):
Between voxel 0 (-z) and voxel 4 (+z)

Paint bond with color (5):
Between voxel 1 (+y) and voxel 3 (-y)

Paint bond with color (6):
Between voxel 1 (-y) and voxel 3 (+y)

Paint bond with color (7):
Between voxel 1 (+z) and voxel 5 (-z)

Paint bond with color (8):
Between voxel 1 (-z) and voxel 5 (+z)

Paint bond with color (9):
Between voxel 3 (+z) and voxel 7 (-z)

Paint bond with color (10):
Between voxel 3 (-z) and voxel 7 (+z)

Paint bond with color (11):
Between voxel 4 (+x) and voxel 5 (-x)

Paint bond with color (12):
Between voxel 4 (-x) and voxel 5 (+x)

Paint bond with color (13):
Between voxel 5 (+y) and voxel 7 (-y)

Paint bond with color (14):
Between voxel 5 (-y) and voxel 7 (+y)

