# Symmetry Tests

In [1]:
%load_ext autoreload
%autoreload 2

In [23]:
import sys

sys.path.append('../')
from algorithm.Voxel import Voxel
from algorithm.Lattice import Lattice
from algorithm.Surroundings import SurroundingsManager
from algorithm.Symmetry import SymmetryDf

import numpy as np
import pandas as pd

In [24]:
#TODO: Create MinDesign which displays Voxel.index for each location
print("SymmetryDf tests\n---\n")

input_lattice = np.load('data/lattice.npy')
print(f'Input lattice:\n{input_lattice}\n')

lattice = Lattice(input_lattice)

# Print statements
print(f'Min design:\n{lattice.MinDesign}\n')
print(f'voxel_list:\n{lattice.voxel_list}\n')

voxel_indices = [str(voxel.index) for voxel in lattice.voxel_list]
print(f'voxel_list indices:\n{", ".join(voxel_indices)}\n')

print(f'coord_list:\n{lattice.coord_list}\n')

surr_manager = SurroundingsManager(lattice)
# print(f'Full surroundings:\n{surr_manager.FullSurroundings}\n')
# print(f'VoxelSurroundings for voxel 0:\n{surr_manager.getVoxelSurroundings(lattice.voxels[0])}\n')
# print(f'VoxelSurroundings for voxel 1:\n{surr_manager.getVoxelSurroundings(lattice.voxels[1])}\n')

symmetry_df = SymmetryDf(lattice, surr_manager)
symmetry_df.compute_all_symmetries()
df = symmetry_df.symmetry_df
df

SymmetryDf tests
---

Input lattice:
[[[1. 1. 1.]
  [1. 0. 1.]
  [1. 1. 1.]]

 [[0. 0. 0.]
  [0. 1. 0.]
  [0. 0. 0.]]

 [[1. 1. 1.]
  [1. 0. 1.]
  [1. 1. 1.]]]

Min design:
[[[1. 1.]
  [1. 0.]]

 [[0. 0.]
  [0. 1.]]]

voxel_list:
[<algorithm.Voxel.Voxel object at 0x1324c4590>, <algorithm.Voxel.Voxel object at 0x13283bb60>, <algorithm.Voxel.Voxel object at 0x14278e630>, <algorithm.Voxel.Voxel object at 0x14278ddc0>, <algorithm.Voxel.Voxel object at 0x14278de20>, <algorithm.Voxel.Voxel object at 0x14278d160>, <algorithm.Voxel.Voxel object at 0x14278d4f0>, <algorithm.Voxel.Voxel object at 0x14278f590>]

voxel_list indices:
0, 1, 2, 3, 4, 5, 6, 7

coord_list:
[(0, 1, 1), (1, 1, 1), (0, 0, 1), (1, 0, 1), (0, 1, 0), (1, 1, 0), (0, 0, 0), (1, 0, 0)]



translation 90° X-axis 180° X-axis 270° X-axis 90° Y-axis 180° Y-axis  \
(1, 4)       False      False       False       False      False       False   
(4, 6)       False      False       False       False      False       False   
(2, 3)       False      False       False       False      False       False   
(2, 6)       False      False       False       False      False       False   
(4, 5)       False      False       False       False      False       False   
(0, 5)       False      False       False       False      False       False   
(1)           True      False        True       False      False        True   
(3, 4)       False      False       False       False      False       False   
(0, 6)       False      False       False       False      False       False   
(1, 7)       False      False       False       False      False       False   
(0, 3)       False      False       False       False      False       False   
(2)           True      False        True       False      False        True   
(0, 2)       False      False       False       False      False       False   
(4)           True      False        True       False      False        True   
(0, 4)       False      False       False       False      False       False   
(2, 4)       False      False       False       False      False       False   
(5, 6)       False      False       False       False      False       False   
(3, 5)       False      False       False       False      False       False   
(1, 6)       False      False       False       False      False       False   
(0, 7)       False      False       False       False      False       False   
(1, 3)       False      False       False       False      False       False   
(4, 7)       False      False       False       False      False       False   
(3, 7)       False      False       False       False      False       False   
(0, 1)       False      False       False       False      False       False   
(3, 6)       False      False       False       False      False       False   
(6, 7)       False      False       False       False      False       False   
(5)           True      False        True       False      False        True   
(1, 5)       False      False       False       False      False       False   
(7)           True      False        True       False      False        True   
(2, 7)       False      False       False       False      False       False   
(5, 7)       False      False       False       False      False       False   
(1, 2)       False      False       False       False      False       False   
(2, 5)       False      False       False       False      False       False   
(3)           True      False        True       False      False        True   
(6)           True      False        True       False      False        True   
(0)           True      False        True       False      False        True   

       270° Y-axis 90° Z-axis 180° Z-axis 270° Z-axis  ...  \
(1, 4)       False      False       False       False  ...   
(4, 6)       False      False       False       False  ...   
(2, 3)       False      False       False       False  ...   
(2, 6)       False      False       False       False  ...   
(4, 5)       False      False       False       False  ...   
(0, 5)       False      False       False       False  ...   
(1)          False      False        True       False  ...   
(3, 4)       False      False       False       False  ...   
(0, 6)       False      False       False       False  ...   
(1, 7)       False      False       False       False  ...   
(0, 3)       False      False       False       False  ...   
(2)          False      False        True       False  ...   
(0, 2)       False      False       False       False  ...   
(4)          False       True        True        True  ...   
(0, 4)       False      False       False       False  ...   
(2, 4)       False      False       False       False 

## View SymDict for each voxel in MinDesign

In [25]:
symmetry_df.print_all_symdicts()

Voxel 0
---
Coordinates: (0, 1, 1) Material: 1.0
Symmetries:
(0): ['translation', '180° X-axis', '180° Y-axis', '90° Z-axis', '180° Z-axis', '270° Z-axis', '180° X-axis + 180° Y-axis', '180° X-axis + 180° Z-axis', '180° X-axis + 270° Z-axis', '180° X-axis + 90° Z-axis', '180° Z-axis + 180° Y-axis', '270° Z-axis + 180° Y-axis', '90° Z-axis + 180° Y-axis']


Voxel 1
---
Coordinates: (1, 1, 1) Material: 1.0
Symmetries:
(1): ['translation', '180° X-axis', '180° Y-axis', '180° Z-axis', '180° X-axis + 180° Y-axis', '180° X-axis + 180° Z-axis', '180° Z-axis + 180° Y-axis']
(1, 2): ['90° Z-axis', '270° Z-axis', '180° X-axis + 270° Z-axis', '180° X-axis + 90° Z-axis', '270° Z-axis + 180° Y-axis', '90° Z-axis + 180° Y-axis']


Voxel 2
---
Coordinates: (0, 0, 1) Material: 1.0
Symmetries:
(1, 2): ['90° Z-axis', '270° Z-axis', '180° X-axis + 270° Z-axis', '180° X-axis + 90° Z-axis', '270° Z-axis + 180° Y-axis', '90° Z-axis + 180° Y-axis']
(2): ['translation', '180° X-axis', '180° Y-axis', '180° Z-a

## Test: Inspect the lattice design

In [27]:
%gui qt

import sys
import numpy as np
from PyQt6.QtWidgets import QApplication
from PyQt6.QtCore import QCoreApplication

sys.path.append('../')
from app.visualize.VisualizeWindow import RunVisualizer

if __name__ == '__main__':
    if not QCoreApplication.instance():
        app = QApplication(sys.argv)
    else:
        app = QCoreApplication.instance()

    # Load the input lattice
    input_lattice = np.load('data/lattice.npy')
    lattice = Lattice(input_lattice)
    print(f'Visualizing MinDesign:\n{lattice.MinDesign}\n')

    visualizeWindow = RunVisualizer(lattice.MinDesign, app)

Visualizing MinDesign:
[[[1. 1.]
  [1. 0.]]

 [[0. 0.]
  [0. 1.]]]

