# Symmetry Tests

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys

sys.path.append('../')
from algorithm.Voxel import Voxel
from algorithm.Lattice import Lattice
from algorithm.Surroundings import SurroundingsManager
from algorithm.Symmetry2 import SymmetryDf

import numpy as np
import pandas as pd

In [3]:
#TODO: Create MinDesign which displays Voxel.index for each location
print("SymmetryManager tests\n---\n")

input_lattice = np.load('data/lattice.npy')
print(f'Input lattice:\n{input_lattice}\n')

lattice = Lattice(input_lattice)
print(f'Min design:\n{lattice.MinDesign}\n')
print(f'VoxelDict:\n{lattice.VoxelDict}\n')

voxel_dict = pd.DataFrame.from_dict(lattice.VoxelDict, orient='index')

print(f'Voxel obj coordinates:\n{[voxel.coordinates for voxel in lattice.VoxelDict.values()]}\n')
print(f'\nVoxel obj indices:\n{[voxel.index for voxel in lattice.VoxelDict.values()]}\n')

surr_manager = SurroundingsManager(lattice)
print(f'Full surroundings:\n{surr_manager.FullSurroundings}\n')
# print(f'VoxelSurroundings for voxel 0:\n{surr_manager.getVoxelSurroundings(lattice.voxels[0])}\n')
# print(f'VoxelSurroundings for voxel 1:\n{surr_manager.getVoxelSurroundings(lattice.voxels[1])}\n')

sym_manager = SymmetryDf(lattice, surr_manager)
sym_manager.compute_all_symmetries()
df = sym_manager.symmetry_df
df

SymmetryManager tests
---

Input lattice:
[[[1. 1. 1.]
  [1. 0. 1.]
  [1. 1. 1.]]

 [[0. 0. 0.]
  [0. 1. 0.]
  [0. 0. 0.]]

 [[1. 1. 1.]
  [1. 0. 1.]
  [1. 1. 1.]]]

Voxel 0 at np_coords: (0, 0, 0), coords: [0 1 1] has material 1.0
Voxel 1 at np_coords: (0, 0, 1), coords: [1 1 1] has material 1.0
Voxel 2 at np_coords: (0, 1, 0), coords: [0 0 1] has material 1.0
Voxel 3 at np_coords: (0, 1, 1), coords: [1 0 1] has material 0.0
Voxel 4 at np_coords: (1, 0, 0), coords: [0 1 0] has material 0.0
Voxel 5 at np_coords: (1, 0, 1), coords: [1 1 0] has material 0.0
Voxel 6 at np_coords: (1, 1, 0), coords: [0 0 0] has material 0.0
Voxel 7 at np_coords: (1, 1, 1), coords: [1 0 0] has material 1.0
Min design:
[[[1. 1.]
  [1. 0.]]

 [[0. 0.]
  [0. 1.]]]

VoxelDict:
{b'\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00': <algorithm.Voxel.Voxel object at 0x130193380>, b'\x01\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x0

translation 90° X-axis 180° X-axis 270° X-axis 90° Y-axis 180° Y-axis  \
(1, 4)       False      False       False       False      False       False   
(4, 6)       False      False       False       False      False       False   
(2, 3)       False      False       False       False      False       False   
(2, 6)       False      False       False       False      False       False   
(4, 5)       False      False       False       False      False       False   
(0, 5)       False      False       False       False      False       False   
(1)           True      False        True       False      False        True   
(3, 4)       False      False       False       False      False       False   
(0, 6)       False      False       False       False      False       False   
(1, 7)       False      False       False       False      False       False   
(0, 3)       False      False       False       False      False       False   
(2)           True      False        True       False      False        True   
(0, 2)       False      False       False       False      False       False   
(4)           True      False        True       False      False        True   
(0, 4)       False      False       False       False      False       False   
(2, 4)       False      False       False       False      False       False   
(5, 6)       False      False       False       False      False       False   
(3, 5)       False      False       False       False      False       False   
(1, 6)       False      False       False       False      False       False   
(0, 7)       False      False       False       False      False       False   
(1, 3)       False      False       False       False      False       False   
(4, 7)       False      False       False       False      False       False   
(3, 7)       False      False       False       False      False       False   
(0, 1)       False      False       False       False      False       False   
(3, 6)       False      False       False       False      False       False   
(6, 7)       False      False       False       False      False       False   
(5)           True      False        True       False      False        True   
(1, 5)       False      False       False       False      False       False   
(7)           True      False        True       False      False        True   
(2, 7)       False      False       False       False      False       False   
(5, 7)       False      False       False       False      False       False   
(1, 2)       False      False       False       False      False       False   
(2, 5)       False      False       False       False      False       False   
(3)           True      False        True       False      False        True   
(6)           True      False        True       False      False        True   
(0)           True      False        True       False      False        True   

       270° Y-axis 90° Z-axis 180° Z-axis 270° Z-axis  ...  \
(1, 4)       False      False       False       False  ...   
(4, 6)       False      False       False       False  ...   
(2, 3)       False      False       False       False  ...   
(2, 6)       False      False       False       False  ...   
(4, 5)       False      False       False       False  ...   
(0, 5)       False      False       False       False  ...   
(1)          False       True        True        True  ...   
(3, 4)       False      False       False       False  ...   
(0, 6)       False      False       False       False  ...   
(1, 7)       False      False       False       False  ...   
(0, 3)       False      False       False       False  ...   
(2)          False      False        True       False  ...   
(0, 2)       False      False       False       False  ...   
(4)          False      False        True       False  ...   
(0, 4)       False      False       False       False  ...   
(2, 4)       False       True       False        True 