# Painting Tests

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import sys

sys.path.append('../')
from algorithm.Voxel import Voxel
from algorithm.Lattice import Lattice
from algorithm.Surroundings import Surroundings
from algorithm.symmetry_df import SymmetryDf
from algorithm.BondPainter import Mesovoxel, BondPainter
from algorithm.RotationDict import VoxelRotater

import numpy as np
import pandas as pd

## Setup: View the lattice

In [35]:
%gui qt

import sys
from PyQt6.QtWidgets import QApplication
from PyQt6.QtCore import QCoreApplication

sys.path.append('../')
from app.design.Designer import RunDesigner

if __name__ == '__main__':
    if not QCoreApplication.instance():
        app = QApplication(sys.argv)
    else:
        app = QCoreApplication.instance()
    
    designer = RunDesigner(app)
    input_lattice = designer.run()
    
    if input_lattice is not None:
        print(f'Lattice received.')
        np.save("data/lattice.npy", input_lattice)
    else:
        print("No lattice received.")

Saved lattice:
[[[1 1 1]
  [0 2 0]
  [1 1 1]]

 [[2 2 2]
  [2 2 2]
  [2 2 2]]

 [[1 1 1]
  [0 2 0]
  [1 1 1]]]

Lattice received.


In [7]:
%gui qt

import sys
import numpy as np
from PyQt6.QtWidgets import QApplication
from PyQt6.QtCore import QCoreApplication

sys.path.append('../noteooks/')
from app.visualize.Visualizer import RunVisualizer

if __name__ == '__main__':
    if not QCoreApplication.instance():
        app = QApplication(sys.argv)
    else:
        app = QCoreApplication.instance()

    # Load the input lattice
    input_lattice = np.load('data/lattice.npy')
    lattice = Lattice(input_lattice)
    print(f'Visualizing UnitCell:\n{lattice.UnitCell}\n')

    visualizeWindow = RunVisualizer(lattice, app)

FileNotFoundError: [Errno 2] No such file or directory: 'data/lattice.npy'

### Setup: Initialize symmetry data structures

In [58]:
input_lattice = np.load('data/lattice.npy')
# print(f'Input lattice:\n{input_lattice}\n')

lattice = Lattice(input_lattice)
surr_manager = Surroundings(lattice)
symmetry_df = SymmetryDf(lattice, surr_manager)
df = symmetry_df.symmetry_df

df

translation 90° X-axis 180° X-axis 270° X-axis 90° Y-axis  \
(2, 8)         False      False       False       False      False   
(2, 3)          True      False       False       False      False   
(10, 13)       False      False       False       False      False   
(7, 8)         False      False        True       False      False   
(7, 14)        False      False       False       False      False   
...              ...        ...         ...         ...        ...   
(5, 14)        False      False       False       False      False   
(12, 15)        True      False       False       False      False   
(3, 10)        False      False       False       False      False   
(7)             True      False       False       False      False   
(10, 14)       False      False       False       False      False   

         180° Y-axis 270° Y-axis 90° Z-axis 180° Z-axis 270° Z-axis  ...  \
(2, 8)         False       False      False       False       False  ...   
(2, 3)         False       False       True        True        True  ...   
(10, 13)       False       False      False       False       False  ...   
(7, 8)          True       False      False       False       False  ...   
(7, 14)        False       False      False       False       False  ...   
...              ...         ...        ...         ...         ...  ...   
(5, 14)        False       False      False       False       False  ...   
(12, 15)       False       False       True        True        True  ...   
(3, 10)        False       False      False       False       False  ...   
(7)            False       False       True        True        True  ...   
(10, 14)       False       False      False       False       False  ...   

         90° X-axis + 270° Y-axis 90° X-axis + 270° Z-axis  \
(2, 8)                      False                    False   
(2, 3)                      False                    False   
(10, 13)                    False                    False   
(7, 8)                      False                    False   
(7, 14)                     False                    False   
...                           ...                      ...   
(5, 14)                     False                    False   
(12, 15)                    False                    False   
(3, 10)                     False                    False   
(7)                         False                    False   
(10, 14)                    False                    False   

         90° X-axis + 90° Z-axis 90° Y-axis + 180° X-axis  \
(2, 8)                     False                    False   
(2, 3)                     False                    False   
(10, 13)                   False                    False   
(7, 8)                     False                    False   
(7, 14)                    False                    False   
...                          ...                      ...   
(5, 14)                    False                    False   
(12, 15)                   False                    False   
(3, 10)                    False                    False   
(7)                        False                    False   
(10, 14)                   False                    False   

         90° Y-axis + 180° Z-axis 90° Y-axis + 270° X-axis  \
(2, 8)                      False                    False   
(2, 3)                      False                    False   
(10, 13)                    False                    False   
(7, 8)                      False                    False   
(7, 14)                     False                    False   
...                           ...                      ...   
(5, 14)                     False                    False   
(12, 15)                    False                    False   
(3, 10)                     False                    False   
(7)                         False                    False   
(10, 14)                    False                    False   

         90° Y-axis + 270° Z-axi

## Mesovoxel initialization tests
### 1. Structural / Complementary voxels

In [61]:
mesovoxel = Mesovoxel(lattice, symmetry_df)

print(f'Structural voxels\n---')
for voxel in mesovoxel.structural_voxels:
    print(f'Voxel {voxel.id} | Coordinates: {voxel.coordinates} Material: {voxel.material}')

print(f'\nComplementary voxels\n---')
for voxel in mesovoxel.complementary_voxels:
    print(f'Voxel {voxel.id} | Coordinates: {voxel.coordinates} Material: {voxel.material}')

Adding voxel 1 to complementary_voxels
---
Has the following symmetries with voxel 0:
['translation', '90° Z-axis', '180° Z-axis', '270° Z-axis', '180° X-axis + 180° Y-axis']

Adding voxel 2 to complementary_voxels
---
Has the following symmetries with voxel 0:
['translation', '90° Z-axis', '180° Z-axis', '270° Z-axis', '180° X-axis + 180° Y-axis']

Adding voxel 3 to complementary_voxels
---
Has the following symmetries with voxel 0:
['translation', '90° Z-axis', '180° Z-axis', '270° Z-axis', '180° X-axis + 180° Y-axis']

Adding voxel 5 to complementary_voxels
---
Has the following symmetries with voxel 4:
['translation', '90° Z-axis', '180° Z-axis', '270° Z-axis', '180° X-axis + 180° Y-axis']

Adding voxel 6 to complementary_voxels
---
Has the following symmetries with voxel 4:
['translation', '90° Z-axis', '180° Z-axis', '270° Z-axis', '180° X-axis + 180° Y-axis']

Adding voxel 7 to complementary_voxels
---
Has the following symmetries with voxel 4:
['translation', '90° Z-axis', '180

### 2. Paint all bonds between structural voxels

In [62]:
bond_painter = BondPainter(lattice, surr_manager, symmetry_df)
bond_painter.paint_mesovoxel(mesovoxel)

Paint bond with color (1):
Between voxel 0 ((0, 0, -1)) and voxel 4 ((0, 0, 1))



### Visualize the painted mesovoxel

In [65]:
%gui qt

import sys
import numpy as np
from PyQt6.QtWidgets import QApplication
from PyQt6.QtCore import QCoreApplication

sys.path.append('../')
from app.visualize.Visualizer import RunVisualizer

if __name__ == '__main__':
    if not QCoreApplication.instance():
        app = QApplication(sys.argv)
    else:
        app = QCoreApplication.instance()

    print(f'Visualizing MinDesign:\n{lattice.MinDesign}\n')
    visualizeWindow = RunVisualizer(bond_painter.lattice, app)

Visualizing MinDesign:
[[[1 1]
  [1 1]]

 [[0 0]
  [0 0]]

 [[0 0]
  [0 0]]

 [[1 1]
  [1 1]]]



## Rotate voxel tests

In [81]:
voxel_rotater = VoxelRotater()
voxel = bond_painter.lattice.get_voxel(0)

voxel.print_bonds()
rot_voxel = voxel_rotater.rotate_voxel(voxel, '90° Z-axis')
rot_voxel.print_bonds()

Voxel 0 (1):
---
 -> +x: 2
 -> -x: -2
 -> +y: 3
 -> -y: -3
 -> +z: 4
 -> -z: 1
Voxel 0 (1):
---
 -> +y: 2
 -> -y: -2
 -> -x: 3
 -> +x: -3
 -> +z: 4
 -> -z: 1


In [45]:
from algorithm.RotationDict import VoxelRotater, NpRotationDict, ScipyRotationDict
from algorithm.Bond import Bond
from algorithm.Voxel import Voxel

scirot_dict = ScipyRotationDict()
rot = scirot_dict.get_rotation('90° Z-axis')

for _, bond in voxel.bonds.items():
    direction = np.array(bond.direction)
    rotated_direction = tuple(np.round(rot(direction)).astype(int))
    print(f'Original direction: {tuple(direction)}, rotated direction: {rotated_direction}')


rotater = VoxelRotater()
rotated_voxel = rotater.rotate_voxel(voxel, '180° X-axis + 180° Y-axis')

print("\nRotated voxel bonds:\n---")
for bond in rotated_voxel.bonds.values():
    print(f'Bond direction: {bond.direction}, color: {bond.color}, type: {bond.type}')


Original direction: (1, 0, 0), rotated direction: (0, 1, 0)
Original direction: (-1, 0, 0), rotated direction: (0, -1, 0)
Original direction: (0, 1, 0), rotated direction: (-1, 0, 0)
Original direction: (0, -1, 0), rotated direction: (1, 0, 0)
Original direction: (0, 0, 1), rotated direction: (0, 0, 1)
Original direction: (0, 0, -1), rotated direction: (0, 0, -1)

Rotated voxel bonds:
---
Bond direction: (-1, 0, 0), color: None, type: None
Bond direction: (1, 0, 0), color: None, type: None
Bond direction: (0, -1, 0), color: None, type: None
Bond direction: (0, 1, 0), color: None, type: None
Bond direction: (0, 0, 1), color: None, type: None
Bond direction: (0, 0, -1), color: 1, type: structural


## Testing the full painting algorithm

In [40]:
input_lattice = np.load('data/lattice.npy')

lattice = Lattice(input_lattice)
surr_manager = Surroundings(lattice)
symmetry_df = SymmetryDf(lattice, surr_manager)

# Bond painter stuff
bond_painter = BondPainter(lattice, symmetry_df)
bond_painter.paint_lattice()

Initializing the mesovoxel...
Coloring the lattice...
Done!


In [41]:
%gui qt

import sys
import numpy as np
from PyQt6.QtWidgets import QApplication
from PyQt6.QtCore import QCoreApplication

sys.path.append('../')
from app.visualize.Visualizer import RunVisualizer

if __name__ == '__main__':
    if not QCoreApplication.instance():
        app = QApplication(sys.argv)
    else:
        app = QCoreApplication.instance()

    print(f'Visualizing MinDesign:\n{lattice.MinDesign}\n')
    visualizeWindow = RunVisualizer(bond_painter.lattice, app)

Visualizing MinDesign:
[[[1 1]
  [1 1]]

 [[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]



In [34]:
# Lists to store combined voxel and bond information
final_df = bond_painter.lattice.final_df()
final_df

Voxel                      Bond Colors               
      ID Material Coordinates          +x -x +y -y +z -z
0      0        1   (0, 1, 2)           2  2  2  2  1  1
1      1        1   (1, 1, 2)          -2 -2 -2 -2  1  1
2      2        1   (0, 0, 2)          -2 -2 -2 -2  1  1
3      3        1   (1, 0, 2)           2  2  2  2  1  1
4      4        0   (0, 1, 1)           3  3  3  3 -1  4
5      5        0   (1, 1, 1)          -3 -3 -3 -3 -1  4
6      6        0   (0, 0, 1)          -3 -3 -3 -3 -1  4
7      7        0   (1, 0, 1)           3  3  3  3 -1  4
8      8        0   (0, 1, 0)           3  3  3  3 -4 -1
9      9        0   (1, 1, 0)          -3 -3 -3 -3 -4 -1
10    10        0   (0, 0, 0)          -3 -3 -3 -3 -4 -1
11    11        0   (1, 0, 0)           3  3  3  3 -4 -1