# Symmetry Tests

In [67]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [76]:
import sys

sys.path.append('../')
from algorithm.Voxel import Voxel
from algorithm.Lattice import Lattice
from algorithm.Surroundings import Surroundings
from algorithm.SymmetryDf import SymmetryDf
from algorithm.BondPainter import Mesovoxel, BondPainter

import numpy as np
import pandas as pd

## Create a desired Lattice

In [60]:
%gui qt

import sys
from PyQt6.QtWidgets import QApplication
from PyQt6.QtCore import QCoreApplication

sys.path.append('../')
from app.design.Designer import RunDesigner

if __name__ == '__main__':
    if not QCoreApplication.instance():
        app = QApplication(sys.argv)
    else:
        app = QCoreApplication.instance()
    
    designer = RunDesigner(app)
    input_lattice = designer.run()
    
    if input_lattice is not None:
        print(f'Lattice received.')
        np.save("data/lattice.npy", input_lattice)
    else:
        print("No lattice received.")

Saved lattice:
[[[1 1]
  [1 1]]

 [[0 0]
  [0 0]]

 [[0 0]
  [0 0]]

 [[1 1]
  [1 1]]]

Lattice received.


### Lattice initialization tests

In [80]:
#TODO: Create MinDesign which displays Voxel.index for each location
print("SymmetryDf tests\n---")

input_lattice = np.load('data/lattice.npy')
print(f'Input lattice:\n{input_lattice}\n')

lattice = Lattice(input_lattice)

# Print statements
print(f'Min design:\n{lattice.MinDesign}\n')
print(f'voxel_list:\n{lattice.voxel_list}\n')

voxel_indices = [str(voxel.id) for voxel in lattice.voxel_list]
print(f'voxel_list ids:\n{", ".join(voxel_indices)}\n')

print(f'coord_list:\n{lattice.coord_list}\n')

SymmetryDf tests
---

Input lattice:
[[[1 1]
  [1 1]]

 [[0 0]
  [0 0]]

 [[0 0]
  [0 0]]

 [[1 1]
  [1 1]]]

Initialized Voxels: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15
With coordinates: (0, 1, 3), (1, 1, 3), (0, 0, 3), (1, 0, 3), (0, 1, 2), (1, 1, 2), (0, 0, 2), (1, 0, 2), (0, 1, 1), (1, 1, 1), (0, 0, 1), (1, 0, 1), (0, 1, 0), (1, 1, 0), (0, 0, 0), (1, 0, 0)
Min design:
[[[1 1]
  [1 1]]

 [[0 0]
  [0 0]]

 [[0 0]
  [0 0]]

 [[1 1]
  [1 1]]]

voxel_list:
[<algorithm.Voxel.Voxel object at 0x2867a3d40>, <algorithm.Voxel.Voxel object at 0x2867a3860>, <algorithm.Voxel.Voxel object at 0x2867baae0>, <algorithm.Voxel.Voxel object at 0x287606630>, <algorithm.Voxel.Voxel object at 0x287606b10>, <algorithm.Voxel.Voxel object at 0x287605be0>, <algorithm.Voxel.Voxel object at 0x287605940>, <algorithm.Voxel.Voxel object at 0x287607e90>, <algorithm.Voxel.Voxel object at 0x287607a40>, <algorithm.Voxel.Voxel object at 0x287606060>, <algorithm.Voxel.Voxel object at 0x287607d10>, <algorith

### Surroundings tests

In [83]:
# Surroundings Tests
surr_manager = Surroundings(lattice)
print(f'Full surroundings:\n{surr_manager.FullSurroundings}\n')
print(f'VoxelSurroundings for voxel 0:\n{surr_manager.voxel_surroundings(lattice.voxel_list[0])}\n')
print(f'VoxelSurroundings for voxel 1:\n{surr_manager.voxel_surroundings(lattice.voxel_list[1])}\n')

Full surroundings:
[[[1 1 1 ... 1 1 1]
  [1 1 1 ... 1 1 1]
  [1 1 1 ... 1 1 1]
  ...
  [1 1 1 ... 1 1 1]
  [1 1 1 ... 1 1 1]
  [1 1 1 ... 1 1 1]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[1 1 1 ... 1 1 1]
  [1 1 1 ... 1 1 1]
  [1 1 1 ... 1 1 1]
  ...
  [1 1 1 ... 1 1 1]
  [1 1 1 ... 1 1 1]
  [1 1 1 ... 1 1 1]]]

VoxelSurroundings for voxel 0:
[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [

## Symmetry Tests
### 1. Initializing SymmetryDf

In [84]:
# Creating a SymmetryDf automatically computes all combinations of symmetries
symmetry_df = SymmetryDf(lattice, surr_manager)
df = symmetry_df.symmetry_df
df

translation 90° X-axis 180° X-axis 270° X-axis 90° Y-axis  \
(2, 8)         False      False       False       False      False   
(2, 3)          True      False       False       False      False   
(10, 13)       False      False       False       False      False   
(7, 8)         False      False        True       False      False   
(7, 14)        False      False       False       False      False   
...              ...        ...         ...         ...        ...   
(5, 14)        False      False       False       False      False   
(12, 15)        True      False       False       False      False   
(3, 10)        False      False       False       False      False   
(7)             True      False       False       False      False   
(10, 14)       False      False       False       False      False   

         180° Y-axis 270° Y-axis 90° Z-axis 180° Z-axis 270° Z-axis  ...  \
(2, 8)         False       False      False       False       False  ...   
(2, 3)         False       False       True        True        True  ...   
(10, 13)       False       False      False       False       False  ...   
(7, 8)          True       False      False       False       False  ...   
(7, 14)        False       False      False       False       False  ...   
...              ...         ...        ...         ...         ...  ...   
(5, 14)        False       False      False       False       False  ...   
(12, 15)       False       False       True        True        True  ...   
(3, 10)        False       False      False       False       False  ...   
(7)            False       False       True        True        True  ...   
(10, 14)       False       False      False       False       False  ...   

         90° X-axis + 180° Z-axis 90° X-axis + 270° Y-axis  \
(2, 8)                      False                    False   
(2, 3)                      False                    False   
(10, 13)                    False                    False   
(7, 8)                      False                    False   
(7, 14)                     False                    False   
...                           ...                      ...   
(5, 14)                     False                    False   
(12, 15)                    False                    False   
(3, 10)                     False                    False   
(7)                         False                    False   
(10, 14)                    False                    False   

         90° X-axis + 90° Z-axis 90° Y-axis + 180° X-axis  \
(2, 8)                     False                    False   
(2, 3)                     False                    False   
(10, 13)                   False                    False   
(7, 8)                     False                    False   
(7, 14)                    False                    False   
...                          ...                      ...   
(5, 14)                    False                    False   
(12, 15)                   False                    False   
(3, 10)                    False                    False   
(7)                        False                    False   
(10, 14)                   False                    False   

         90° Y-axis + 180° Z-axis 90° Y-axis + 270° X-axis  \
(2, 8)                      False                    False   
(2, 3)                      False                    False   
(10, 13)                    False                    False   
(7, 8)                      False                    False   
(7, 14)                     False                    False   
...                           ...                      ...   
(5, 14)                     False                    False   
(12, 15)                    False                    False   
(3, 10)                     False                    False   
(7)                         False                    False   
(10, 14)                    False                    False   

         90° Y-axis + 270° Z-axi

### 2. View SymDict for each voxel in MinDesign

In [82]:
symmetry_df.print_all_symdicts()

Voxel 0
---
Coordinates: (0, 1, 3) Material: 1
Symmetries:
(0): ['translation', '90° Z-axis', '180° Z-axis', '270° Z-axis', '180° Y-axis + 180° X-axis']
(0, 1): ['translation', '90° Z-axis', '180° Z-axis', '270° Z-axis', '180° Y-axis + 180° X-axis']
(0, 2): ['translation', '90° Z-axis', '180° Z-axis', '270° Z-axis', '180° Y-axis + 180° X-axis']
(0, 3): ['translation', '90° Z-axis', '180° Z-axis', '270° Z-axis', '180° Y-axis + 180° X-axis']
(0, 12): ['180° X-axis', '180° Y-axis', '180° X-axis + 180° Z-axis', '180° X-axis + 90° Z-axis', '180° Y-axis + 180° Z-axis', '180° Y-axis + 270° Z-axis', '180° Y-axis + 90° Z-axis', '270° Z-axis + 180° X-axis']
(0, 13): ['180° X-axis', '180° Y-axis', '180° X-axis + 180° Z-axis', '180° X-axis + 90° Z-axis', '180° Y-axis + 180° Z-axis', '180° Y-axis + 270° Z-axis', '180° Y-axis + 90° Z-axis', '270° Z-axis + 180° X-axis']
(0, 14): ['180° X-axis', '180° Y-axis', '180° X-axis + 180° Z-axis', '180° X-axis + 90° Z-axis', '180° Y-axis + 180° Z-axis', '180° 

## Sanity Check: Inspect the lattice design

In [86]:
%gui qt

import sys
import numpy as np
from PyQt6.QtWidgets import QApplication
from PyQt6.QtCore import QCoreApplication

sys.path.append('../')
from app.visualize.Visualizer import RunVisualizer

if __name__ == '__main__':
    if not QCoreApplication.instance():
        app = QApplication(sys.argv)
    else:
        app = QCoreApplication.instance()

    # Load the input lattice
    input_lattice = np.load('data/lattice.npy')
    lattice = Lattice(input_lattice)
    print(f'Visualizing MinDesign:\n{lattice.MinDesign}\n')

    visualizeWindow = RunVisualizer(lattice, app)

Visualizing MinDesign:
[[[1 1]
  [1 1]]

 [[0 0]
  [0 0]]

 [[0 0]
  [0 0]]

 [[1 1]
  [1 1]]]



# Mesovoxel initialization tests

In [72]:
mesovoxel = Mesovoxel(lattice, symmetry_df)

voxel1_partner_symdict = symmetry_df.partner_symdict(1)

print(f'Voxel 1 partner_symdict:')
for key, value in voxel1_partner_symdict.items():
    print(f'{key}: {value}')

print(f'\nStructural voxels\n---')
for voxel in mesovoxel.structural_voxels:
    print(f'Voxel {voxel.id} Coordinates: {voxel.coordinates} Material: {voxel.material}')

print(f'\nComplementary voxels\n---')
for voxel in mesovoxel.complementary_voxels:
    print(f'Voxel {voxel.id} Coordinates: {voxel.coordinates} Material: {voxel.material}')

Adding voxel 1 to complementary_voxels
---
Has the following symmetries with voxel 0:
['translation', '90° Z-axis', '180° Z-axis', '270° Z-axis', '180° Y-axis + 180° X-axis']

Adding voxel 2 to complementary_voxels
---
Has the following symmetries with voxel 0:
['translation', '90° Z-axis', '180° Z-axis', '270° Z-axis', '180° Y-axis + 180° X-axis']

Adding voxel 3 to complementary_voxels
---
Has the following symmetries with voxel 0:
['translation', '90° Z-axis', '180° Z-axis', '270° Z-axis', '180° Y-axis + 180° X-axis']

Adding voxel 5 to complementary_voxels
---
Has the following symmetries with voxel 4:
['translation', '90° Z-axis', '180° Z-axis', '270° Z-axis', '180° Y-axis + 180° X-axis']

Adding voxel 6 to complementary_voxels
---
Has the following symmetries with voxel 4:
['translation', '90° Z-axis', '180° Z-axis', '270° Z-axis', '180° Y-axis + 180° X-axis']

Adding voxel 7 to complementary_voxels
---
Has the following symmetries with voxel 4:
['translation', '90° Z-axis', '180

# Test some painting

In [73]:
#TODO: Be able to visualize bond painting
bond_painter = BondPainter(lattice, surr_manager, symmetry_df)
bond_painter.paint_mesovoxel(mesovoxel)

Paint bond with color (1):
Between voxel 0 ((0, 0, -1)) and voxel 4 ((0, 0, 1))



## Visualize the painted mesovoxel

In [74]:
%gui qt

import sys
import numpy as np
from PyQt6.QtWidgets import QApplication
from PyQt6.QtCore import QCoreApplication

sys.path.append('../')
from app.visualize.Visualizer import RunVisualizer

if __name__ == '__main__':
    if not QCoreApplication.instance():
        app = QApplication(sys.argv)
    else:
        app = QCoreApplication.instance()

    print(f'Visualizing MinDesign:\n{lattice.MinDesign}\n')
    visualizeWindow = RunVisualizer(bond_painter.lattice, app)

Visualizing MinDesign:
[[[1 1]
  [1 1]]

 [[0 0]
  [0 0]]

 [[0 0]
  [0 0]]

 [[1 1]
  [1 1]]]

Initialized Voxels: 0, 1, 2, 3, 4, 5, 6, 7
With coordinates: (0, 1, 1), (1, 1, 1), (0, 0, 1), (1, 0, 1), (0, 1, 0), (1, 1, 0), (0, 0, 0), (1, 0, 0)
Filled partner: Voxel 0 [0.0] ---(1, 0, 0)---> Voxel 1 [0.0]
Filled partner: Voxel 0 [0.0] ---(-1, 0, 0)---> Voxel 1 [0.0]
Filled partner: Voxel 0 [0.0] ---(0, 1, 0)---> Voxel 2 [0.0]
Filled partner: Voxel 0 [0.0] ---(0, -1, 0)---> Voxel 2 [0.0]
Filled partner: Voxel 0 [0.0] ---(0, 0, 1)---> Voxel 4 [0.0]
Filled partner: Voxel 0 [0.0] ---(0, 0, -1)---> Voxel 4 [0.0]
Filled partner: Voxel 1 [0.0] ---(0, 1, 0)---> Voxel 3 [0.0]
Filled partner: Voxel 1 [0.0] ---(0, -1, 0)---> Voxel 3 [0.0]
Filled partner: Voxel 1 [0.0] ---(0, 0, 1)---> Voxel 5 [0.0]
Filled partner: Voxel 1 [0.0] ---(0, 0, -1)---> Voxel 5 [0.0]
Filled partner: Voxel 2 [0.0] ---(1, 0, 0)---> Voxel 3 [0.0]
Filled partner: Voxel 2 [0.0] ---(-1, 0, 0)---> Voxel 3 [0.0]
Filled partner: Vo